const configtext = [

//右から書く
//0
{title:"الإعدادات",
graphics:"الرسومات",
fullscreen:"شاشة كاملة",
on:"تشغيل •",
off:"إيقاف •",
displayquality:"جودة العرض",
low:"منخفضة",
middle:"متوسطة",
high:"عالية",
ifthe1:"إذا تعطلت اللعبة، *",
ifthe2:"يرجى استخدام هذا الخيار.",
lang:"اللغة",
volume:"مستوى الصوت",
mastervolume:"مستوى الصوت العام",
bgm:"موسيقى الخلفية",
soundeffect:"المؤثرات الصوتية",
voice:"الصوت",
input:"الإدخال",
pc:"الكمبيوتر الشخصي",
mouseandqwer:"الماوس و QWER",
clickanddrag:"(انقر واسحب)",
uemigi:"↑→↓← و ZXCAS",
wasdandqecx:"WASD و QECX",
click0:"(انقر)",
gamepad:"لوحة الألعاب",
smartphoneortablet:"الهاتف الذكي أو الجهاز اللوحي",
touchgestures:"إيماءات اللمس",
onkeyboard:"على لوحة المفاتيح",
onmouseandkeyboard:"ماوس لوحة",
customize:"تخصيص",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"هجوم و موافق",
skill1andcancel: "المهارة 1 و'إلغاء",
skill2:"المهارة 2",
skill3:"المهارة 3",
skill4:"المهارة 4",
pause:"إيقاف مؤقت",
config:"الإعدادات",
mute:"كتم الصوت",
vibration:"الاهتزاز",
mousedrag:"سحب الماوس",
click1:"النقر",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"مسافة",
c:"C",
m:"M",
drag:"سحب",
lowspecmode:"وضع المواصفات المنخفضة",
back:"رجوع",
resetgame:"إعادة ضبط اللعبة",
escape:"Esc",
enter:"Enter",
loading:"جاري التحميل...",
title1:"هيماري مييمي ضد السوكوبوس",
title2:"لعبة إطلاق النار",
gamestart:"بدء اللعبة",
specialthanks:"شكر خاص",
konnichiwa:"مرحبًا. أنا مييمي هيماري.",
kyouha:"اليوم، سأقوم بالقضاء على ثلاث سوكوبوس.",
thisgameq:"تستخدم هذه اللعبة الماوس ومفاتيح QWER.",
thisgamew:"تستخدم هذه اللعبة مفاتيح WASD.",
thisgameup:"تستخدم هذه اللعبة مفاتيح الأسهم.",
thisgamepad:"تستخدم هذه اللعبة لوحة الألعاب.",
openning1:"اجمع العملات واستخدمها في متجر الطائرات بدون طيار الذي ينزل من الأعلى",
openning2:"لشراء المعدات والمهارات. حسنًا، لنبدأ.",
voiceq:"ها نحن ذا!",
voicew:"ها هي تذهب!",
voicee:"مهلاً!",
voicer:"أوووه!",
win:"لقد فزت! لنستمر على هذا المنوال.",
dead:"لقد انتهيت.",
gameend:"هذه هي نهاية اللعبة. أحسنت.",
continue:"شكرًا لك على اللعب.",
soundtest:"اختبار الصوت",
irasshai:"مرحبًا بك!",
thanks:"شكرًا جزيلاً.",
tap:"النقر"},



//1
{title:"Konfiqurasiya",
graphics:"Qrafika",
fullscreen:"Tam ekran",
on:"• Yandır",
off:"• Söndür",
displayquality:"Ekran keyfiyyəti",
low:"Aşağı",
middle:"Orta",
high:"Yüksək",
ifthe1:"* Əgər oyun çökürsə,",
ifthe2:"zəhmət olmasa bundan istifadə edin.",
lang:"Dil",
volume:"Səs həcmi",
mastervolume:"Ümumi səs həcmi",
bgm:"BGM",
soundeffect:"Səs effektləri",
voice:"Səs",
input:"Giriş",
pc:"PC",
mouseandqwer:"Siçan & QWER",
clickanddrag:"(Çəkib buraxın)",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"(Klik)",
gamepad:"Oyun Padı",
smartphoneortablet:"Ağıllı Telefon və ya Planşet",
touchgestures:"Ekran toxunuş jestləri",
onkeyboard:"Klaviaturada",
onmouseandkeyboard:"Mouse & Klaviaturada",
customize:"Fərdiləşdir",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Hücum & OK",
skill1andcancel:"Bacarıq1 & Ləğv",
skill2:"Bacarıq2",
skill3:"Bacarıq3",
skill4:"Bacarıq4",
pause:"Dayan",
config:"Konfiqurasiya",
mute:"Səsini kəs",
vibration:"Vibrasiya",
mousedrag:"Siçanı sürüklə",
click1:"Klik",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Boşluq",
c:"C",
m:"M",
drag:"Sürüklə",
lowspecmode:"aşağı spesifikasiya rejimi",
back:"geri",
resetgame:"oyunu sıfırla",
escape:"Esc",
enter:"Enter",
loading:"Yüklənir...",
title1:"Himari Meimei VS Succubus",
title2:"Atış Oyunu",
gamestart:"Oyunu Başla",
specialthanks:"Təşəkkürlər",
konnichiwa:"Salam. Mən Meimei Himariyam.",
kyouha:"Bu gün üç succubunu məğlub edəcəyəm.",
thisgameq:"Bu oyun siçan və QWER düymələrindən istifadə edir.",
thisgamew:"Bu oyun WASD düymələrindən istifadə edir.",
thisgameup:"Bu oyun ox düymələrindən istifadə edir.",
thisgamepad:"Bu oyun gamepad-dən istifadə edir.",
openning1:"Sikkələri toplayın və dron mağazasında istifadə edin",
openning2:"Avadanlıq və bacarıq almaq üçün istifadə edin",
voiceq:"Başlayıram!",
voicew:"Getdi!",
voicee:"Hey!",
voicer:"Ooohhhh!",
win:"Mən qazandım! Belə davam edək.",
dead:"Bitirdim.",
gameend:"Oyun sona çatdı. Əla iş.",
continue:"Oynadığınız üçün təşəkkür edirik.",
soundtest:"Səs Testi",
irasshai:"Xoş gəlmisiniz!",
thanks:"Çox sağ olun.",
tap:"Tap"},


//2
{title:"কনফিগ",
graphics:"গ্রাফিক্স",
fullscreen:"ফুল স্ক্রিন",
on:"• অন",
off:"• অফ",
displayquality:"ডিসপ্লে কোয়ালিটি",
low:"লো",
middle:"মিডল",
high:"হাই",
ifthe1:"* যদি গেম ক্র্যাশ করে,",
ifthe2:"অনুগ্রহ করে এটি ব্যবহার করুন।",
lang:"ভাষা",
volume:"ভলিউম",
mastervolume:"মাস্টার ভলিউম",
bgm:"বিজিএম",
soundeffect:"সাউন্ড ইফেক্ট",
voice:"ভয়েস",
input:"ইনপুট",
pc:"পিসি",
mouseandqwer:"মাউস ও QWER",
clickanddrag:"( ক্লিক ও ড্র্যাগ )",
uemigi:"↑→↓← ও ZXCAS",
wasdandqecx:"WASD ও QECX",
click0:"( ক্লিক )",
gamepad:"গেম প্যাড",
smartphoneortablet:"স্মার্টফোন বা ট্যাবলেট",
touchgestures:"টাচ জেসচার",
onkeyboard:"কীবোর্ডে",
onmouseandkeyboard:"মাউস ও কীবোর্ডে",
customize:"কাস্টমাইজ",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"আক্রমণ ও ঠিক আছে",
skill1andcancel:"স্কিল১ ও বাতিল",
skill2:"স্কিল২",
skill3:"স্কিল৩",
skill4:"স্কিল৪",
pause:"পজ",
config:"কনফিগ",
mute:"মিউট",
vibration:"ভাইব্রেশন",
mousedrag:"মাউস ড্র্যাগ",
click1:"ক্লিক",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"স্পেস",
c:"C",
m:"M",
drag:"ড্র্যাগ",
lowspecmode:"নিম্ন স্পেস মোড",
back:"পিছনে",
resetgame:"গেম রিসেট",
escape:"Esc",
enter:"Enter",
loading:"লোড হচ্ছে...",
title1:"হিমারি মেইমেই বনাম সাকুবাস",
title2:"শুটিং গেম",
gamestart:"গেম শুরু করুন",
specialthanks:"বিশেষ ধন্যবাদ",
konnichiwa:"হ্যালো। আমি মেইমেই হিমারি।",
kyouha:"আজ আমি তিনটি সাকুবাসকে পরাজিত করতে যাচ্ছি।",
thisgameq:"এই গেমে মাউস এবং QWER কী ব্যবহার হয়।",
thisgamew:"এই গেমে WASD কী ব্যবহার হয়।",
thisgameup:"এই গেমে অ্যারো কী ব্যবহার হয়।",
thisgamepad:"এই গেমে গেমপ্যাড ব্যবহার হয়।",
openning1:"কয়েন সংগ্রহ করুন এবং ড্রোন শপে ব্যবহার করুন",
openning2:"সরঞ্জাম ও দক্ষতা কিনুন। ঠিক আছে, শুরু করা যাক।",
voiceq:"চল শুরু করি!",
voicew:"এই গেল!",
voicee:"এই!",
voicer:"ওহহহহ!",
win:"আমি জিতেছি! এভাবেই চালিয়ে যাই।",
dead:"আমি শেষ।",
gameend:"গেম শেষ। দারুণ কাজ।",
continue:"খেলোয়ার জন্য ধন্যবাদ।",
soundtest:"সাউন্ড টেস্ট",
irasshai:"স্বাগতম!",
thanks:"অনেক অনেক ধন্যবাদ।",
tap:"ট্যাপ"},


//3
{title:"设置",
graphics:"图形",
fullscreen:"全屏",
on:"• 开启",
off:"• 关闭",
displayquality:"显示质量",
low:"低",
middle:"中",
high:"高",
ifthe1:"* 如果游戏崩溃，",
ifthe2:"请使用此选项。",
lang:"语言",
volume:"音量",
mastervolume:"主音量",
bgm:"背景音乐",
soundeffect:"音效",
voice:"语音",
input:"输入",
pc:"PC",
mouseandqwer:"鼠标 & QWER",
clickanddrag:"( 点击 & 拖动 )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( 点击 )",
gamepad:"手柄",
smartphoneortablet:"智能手机或平板",
touchgestures:"触控手势",
onkeyboard:"仅键盘",
onmouseandkeyboard:"鼠标与键盘",
customize:"自定义",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"攻击 & 确认",
skill1andcancel:"技能1 & 取消",
skill2:"技能2",
skill3:"技能3",
skill4:"技能4",
pause:"暂停",
config:"设置",
mute:"静音",
vibration:"振动",
mousedrag:"鼠标拖拽",
click1:"点击",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"空格",
c:"C",
m:"M",
drag:"拖拽",
lowspecmode:"低配置模式",
back:"返回",
resetgame:"重置游戏",
escape:"Esc",
enter:"Enter",
loading:"正在加载...",
title1:"冥鸣日葵 VS 魅魔",
title2:"射击游戏",
gamestart:"开始游戏",
specialthanks:"特别鸣谢",
konnichiwa:"大家好，我是日向美美。",
kyouha:"今天，我要击败三只魅魔。",
thisgameq:"本游戏使用鼠标和 QWER 键操作。",
thisgamew:"本游戏使用 WASD 键操作。",
thisgameup:"本游戏使用方向键操作。",
thisgamepad:"本游戏使用手柄操作。",
openning1:"收集金币，并在从上方降落的无人机商店中",
openning2:"购买装备和技能。好，让我们开始吧。",
voiceq:"开始啦！",
voicew:"看它飞走了！",
voicee:"嘿！",
voicer:"噢——！",
win:"我赢了！就照这样继续下去吧。",
dead:"我玩完了。",
gameend:"游戏到此结束。干得漂亮。",
continue:"感谢您的游玩。",
soundtest:"音效测试",
irasshai:"欢迎光临！",
thanks:"非常感谢。",
tap:"轻点"},


//4
{title:"設定",
graphics:"圖形",
fullscreen:"全螢幕",
on:"• 開啟",
off:"• 關閉",
displayquality:"顯示品質",
low:"低",
middle:"中",
high:"高",
ifthe1:"* 若遊戲發生當機，",
ifthe2:"請使用此設定。",
lang:"語言",
volume:"音量",
mastervolume:"總音量",
bgm:"背景音樂",
soundeffect:"音效",
voice:"語音",
input:"輸入",
pc:"PC",
mouseandqwer:"滑鼠與 QWER",
clickanddrag:"( 點擊並拖曳 )",
uemigi:"↑→↓← 與 ZXCAS",
wasdandqecx:"WASD 與 QECX",
click0:"( 點擊 )",
gamepad:"遊戲手把",
smartphoneortablet:"智慧型手機或平板",
touchgestures:"觸控手勢",
onkeyboard:"僅鍵盤",
onmouseandkeyboard:"滑鼠與鍵盤",
customize:"自訂",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"攻擊 & 確定",
skill1andcancel:"技能1 & 取消",
skill2:"技能2",
skill3:"技能3",
skill4:"技能4",
pause:"暫停",
config:"設定",
mute:"靜音",
vibration:"震動",
mousedrag:"滑鼠拖曳",
click1:"點擊",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"空格鍵",
c:"C",
m:"M",
drag:"拖曳",
lowspecmode:"低畫質模式",
back:"返回",
resetgame:"重置遊戲",
escape:"Esc",
enter:"Enter",
loading:"載入中...",
title1:"冥鸣日葵 VS 魅魔",
title2:"射擊遊戲",
gamestart:"開始遊戲",
specialthanks:"特別感謝",
konnichiwa:"大家好，我是日向美美。",
kyouha:"今天，我要擊敗三隻魅魔。",
thisgameq:"本遊戲使用滑鼠和 QWER 鍵。",
thisgamew:"本遊戲使用 WASD 鍵。",
thisgameup:"本遊戲使用方向鍵。",
thisgamepad:"本遊戲使用遊戲手把。",
openning1:"收集金幣，並在從上方降下的無人機商店中",
openning2:"購買裝備和技能。好啦，我們開始吧。",
voiceq:"來吧！",
voicew:"看它飛走了！",
voicee:"嘿！",
voicer:"噢——！",
win:"我贏了！就這樣繼續下去吧。",
dead:"我玩完了。",
gameend:"遊戲到此結束。做得好。",
continue:"感謝您的遊玩。",
soundtest:"音效測試",
irasshai:"歡迎光臨！",
thanks:"非常感謝。",
tap:"點擊"},


//5
{title:"Config",
graphics:"Graphics",
fullscreen:"Full Screen",
on:"• On",
off:"• Off",
displayquality:"Display Quality",
low:"Low",
middle:"Middle",
high:"High",
ifthe1:"* if the game crashes,",
ifthe2:"please use this.",
lang:"Language",
volume:"Volume",
mastervolume:"Master Volume",
bgm:"BGM",
soundeffect:"Sound Effect",
voice:"Voice",
input:"Input",
pc:"PC",
mouseandqwer:"Mouse & QWER",
clickanddrag:"( Click & Drag )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( Click )",
gamepad:"Game Pad",
smartphoneortablet:"Smart Phone or Tablet",
touchgestures:"Touch Gestures",
onkeyboard:"On Keyboard",
onmouseandkeyboard:"On Mouse & Keyboard",
customize:"Customize",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Attack & OK",
skill1andcancel:"Skill1 & Cancel",
skill2:"Skill2",
skill3:"Skill3",
skill4:"Skill4",
pause:"Pause",
config:"Config",
mute:"Mute",
vibration:"Vibration",
mousedrag:"Mouse Drag",
click1:"Click",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Space",
c:"C",
m:"M",
drag:"Drag",
lowspecmode:"Low Spec Mode",
back:"Back",
resetgame:"Reset Game",
escape:"Esc",
enter:"Enter",
loading:"Loading...",
title1:"Himari Meimei VS Succubus",
title2:"Shoot 'Em Up Game",
gamestart:"Start Game",
specialthanks:"Special Thanks",
konnichiwa:"Hello. I'm Meimei Himari.",
kyouha:"Today, I'm going to take down three succubi.",
thisgameq:"This game uses the mouse and the QWER keys.",
thisgamew:"This game uses the WASD keys.",
thisgameup:"This game uses the arrow keys.",
thisgamepad:"This game uses a gamepad.",
openning1:"Collect coins and use them at the drone shop",
openning2:"to purchase equipment and skills. Alright, let's get started.",
voiceq:"Here we go!",
voicew:"There it goes!",
voicee:"Hey!",
voicer:"Ooohhhh!",
win:"I won! Let's keep going like this.",
dead:"I'm done.",
gameend:"That's the end of the game. Good job.",
continue:"Thank you for playing.",
soundtest:"Sound Test",
irasshai:"Welcome!",
thanks:"Thank you very much.",
tap:"Tap"},


//6
{title:"Configuration",
graphics:"Graphismes",
fullscreen:"Plein écran",
on:"• Activé",
off:"• Désactivé",
displayquality:"Qualité d'affichage",
low:"Faible",
middle:"Moyenne",
high:"Élevée",
ifthe1:"* Si le jeu plante,",
ifthe2:"veuillez utiliser ce réglage.",
lang:"Langue",
volume:"Volume",
mastervolume:"Volume général",
bgm:"Musique de fond",
soundeffect:"Effets sonores",
voice:"Voix",
input:"Commandes",
pc:"PC",
mouseandqwer:"Souris et QWER",
clickanddrag:"(Clic et glisser)",
uemigi:"↑→↓← et ZXCAS",
wasdandqecx:"WASD et QECX",
click0:"(Clic)",
gamepad:"Manette",
smartphoneortablet:"Smartphone ou tablette",
touchgestures:"Gestes tactiles",
onkeyboard:"Sur le clavier",
onmouseandkeyboard:"Sur la souris et le clavier",
customize:"Personnaliser",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Attaque & OK",
skill1andcancel:"Compétence 1 & Annuler",
skill2:"Compétence 2",
skill3:"Compétence 3",
skill4:"Compétence 4",
pause:"Pause",
config:"Configuration",
mute:"Sourdine",
vibration:"Vibration",
mousedrag:"Glisser",
click1:"Cliquer",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Espace",
c:"C",
m:"M",
drag:"Glisser",
lowspecmode:"mode bas débit",
back:"retour",
resetgame:"réinitialiser la partie",
escape:"Échap",
enter:"Enter",
loading:"Chargement en cours...",
title1:"Himari Meimei VS Succube",
title2:"Jeu de tir",
gamestart:"Lancer le jeu",
specialthanks:"Remerciements",
konnichiwa:"Bonjour. Je m'appelle Meimei Himari.",
kyouha:"Aujourd'hui, je vais venir à bout de trois succubes.",
thisgameq:"Ce jeu se joue à l'aide de la souris et des touches QWER.",
thisgamew:"Ce jeu se joue à l'aide des touches WASD.",
thisgameup:"Ce jeu se joue à l'aide des touches fléchées.",
thisgamepad:"Ce jeu se joue à l'aide d'une manette.",
openning1:"Récupérez des pièces, utilisez les en boutique",
openning2:"acheter de l'équipement et des compétences. Bon, c'est parti.",
voiceq:"C'est parti !",
voicew:"Et voilà !",
voicee:"Hé !",
voicer:"Ooohhhh !",
win:"J'ai gagné ! Continuons comme ça.",
dead:"J'ai terminé.",
gameend:"C'est la fin du jeu. Bravo.",
continue:"Merci d'avoir joué.",
soundtest:"Test sonore",
irasshai:"Bienvenue !",
thanks:"Merci beaucoup.",
tap:"Taper", },

//7
{title:"Einstellungen",
graphics:"Grafik",
fullscreen:"Vollbild",
on:"• Ein",
off:"• Aus",
displayquality:"Bildqualität",
low:"Niedrig",
middle:"Mittel",
high:"Hoch",
ifthe1:"* Falls das Spiel abstürzt,",
ifthe2:"verwende bitte diese Einstellung.",
lang:"Sprache",
volume:"Lautstärke",
mastervolume:"Gesamtlautstärke",
bgm:"Hintergrundmusik",
soundeffect:"Soundeffekte",
voice:"Stimmen",
input:"Steuerung",
pc:"PC",
mouseandqwer:"Maus & QWER",
clickanddrag:"(Klicken & Ziehen)",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"(Klicken)",
gamepad:"Gamepad",
smartphoneortablet:"Smartphone oder Tablet",
touchgestures:"Touch-Gesten",
onkeyboard:"Auf Tastatur",
onmouseandkeyboard:"Auf Maus & Tastatur",
customize:"Anpassen",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Angriff & OK",
skill1andcancel:"Fähigkeit 1 & Abbrechen",
skill2:"Fähigkeit 2",
skill3:"Fähigkeit 3",
skill4:"Fähigkeit 4",
pause:"Pause",
config:"Einstellungen",
mute:"Stummschalten",
vibration:"Vibration",
mousedrag:"Maus ziehen",
click1:"Klicken",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Leertaste",
c:"C",
m:"M",
drag:"Ziehen",
lowspecmode:"Low Spec Modus",
back:"Zurück",
resetgame:"Spiel zurücksetzen",
escape:"Esc",
enter:"Enter",
loading:"Wird geladen...",
title1:"Himari Meimei VS Succubus",
title2:"Shooter-Spiel",
gamestart:"Spiel starten",
specialthanks:"Besonderer Dank",
konnichiwa:"Hallo. Ich bin Meimei Himari.",
kyouha:"Heute werde ich drei Succubi besiegen.",
thisgameq:"Dieses Spiel wird mit der Maus und den Tasten QWER gesteuert.",
thisgamew:"Dieses Spiel wird mit den WASD-Tasten gesteuert.",
thisgameup:"Dieses Spiel wird mit den Pfeiltasten gesteuert.",
thisgamepad:"Dieses Spiel wird mit einem Gamepad gesteuert.",
openning1:"Sammle Münzen und gib sie im Drohnen Shop aus ",
openning2:"Ausrüstung und Fähigkeiten zu kaufen. Okay, legen wir los.",
voiceq:"Los geht's!",
voicew:"Da fliegt es hin!",
voicee:"Hey!",
voicer:"Ooohhhh!",
win:"Ich habe gewonnen! Machen wir so weiter.",
dead:"Ich bin fertig.",
gameend:"Das ist das Ende des Spiels. Gut gemacht.",
continue:"Vielen Dank fürs Spielen.",
soundtest:"Soundtest",
irasshai:"Willkommen!",
thanks:"Vielen Dank.",
tap:"Tippen", },


//8
{title:"સેટિંગ",
graphics:"ગ્રાફિક્સ",
fullscreen:"ફુલ સ્ક્રીન",
on:"• ચાલુ",
off:"• બંધ",
displayquality:"ડિસ્પ્લે ગુણવત્તા",
low:"નીચું",
middle:"મધ્યમ",
high:"ઊંચું",
ifthe1:"* જો ગેમ ક્રેશ થાય,",
ifthe2:"કૃપા કરીને આનો ઉપયોગ કરો.",
lang:"ભાષા",
volume:"વોલ્યુમ",
mastervolume:"માસ્ટર વોલ્યુમ",
bgm:"BGM",
soundeffect:"ધ્વનિ અસર",
voice:"અવાજ",
input:"ઇનપુટ",
pc:"PC",
mouseandqwer:"માઉસ & QWER",
clickanddrag:"( ક્લિક & ડ્રેગ )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( ક્લિક )",
gamepad:"ગેમ પેડ",
smartphoneortablet:"સ્માર્ટ ફોન અથવા ટેબ્લેટ",
touchgestures:"ટચ જેશ્ચર્સ",
onkeyboard:"કીબોર્ડ પર",
onmouseandkeyboard:"માઉસ અને કીબોર્ડ પર",
customize:"કસ્ટમાઇઝ",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"એટેક & OK",
skill1andcancel:"સ્કિલ1 & કેન્સલ",
skill2:"સ્કિલ2",
skill3:"સ્કિલ3",
skill4:"સ્કિલ4",
pause:"પોઝ",
config:"સેટિંગ",
mute:"મ્યુટ",
vibration:"વાઇબ્રેશન",
mousedrag:"માઉસ ડ્રેગ",
click1:"ક્લિક",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"સ્પેસ",
c:"C",
m:"M",
drag:"ડ્રેગ",
lowspecmode:"નીચી સ્પેસ મોડ",
back:"પાછું",
resetgame:"રમત રીસેટ",
escape:"Esc",
enter:"Enter",
loading:"લોડ થઈ રહ્યું છે...",
title1:"હિમારી મેઈમેઈ વિ.સક્કૂબસ",
title2:"શૂટિંગ ગેમ",
gamestart:"ગેમ શરૂ કરો",
specialthanks:"વિશેષ આભાર",
konnichiwa:"હેલો. હું મેઈમેઈ હિમારી છું.",
kyouha:"આજે, હું ત્રણ સક્કૂબીઓને હરાવીશ.",
thisgameq:"આ ગેમ માઉસ અને QWER કીઝનો ઉપયોગ કરે છે.",
thisgamew:"આ ગેમ WASD કીઝનો ઉપયોગ કરે છે.",
thisgameup:"આ ગેમ એરો કીઝનો ઉપયોગ કરે છે.",
thisgamepad:"આ ગેમ ગેમપેડનો ઉપયોગ કરે છે.",
openning1:"સિક્કા એકત્રિત કરો અને ડ્રોન દુકાનમાં ઉપયોગ કરો",
openning2:"ઉપકરણો અને કુશળતાઓ ખરીદો. બરાબર, ચાલો શરૂ કરીએ.",
voiceq:"ચાલો શરૂ કરીએ!",
voicew:"એ જાય છે!",
voicee:"હે!",
voicer:"ઓહહહહ!",
win:"હું જીતી ગયો! આવું જ ચાલુ રાખીએ.",
dead:"હું પૂરું કરી લીધું.",
gameend:"આ રમતનો અંત છે. શાબાશ.",
continue:"રમવા બદલ આભાર.",
soundtest:"ધ્વનિ પરીક્ષણ",
irasshai:"સ્વાગત છે!",
thanks:"ખૂબ ખૂબ આભાર.",
tap:"ટૅપ"},


//9
{title:"सेटिंग",
graphics:"ग्राफिक्स",
fullscreen:"फुल स्क्रीन",
on:"• चालू",
off:"• बंद",
displayquality:"डिस्प्ले गुणवत्ता",
low:"कम",
middle:"मध्यम",
high:"उच्च",
ifthe1:"* यदि गेम क्रैश हो जाता है,",
ifthe2:"तो कृपया इसका उपयोग करें।",
lang:"भाषा",
volume:"वॉल्यूम",
mastervolume:"मास्टर वॉल्यूम",
bgm:"बीजीएम",
soundeffect:"साउंड इफ़ेक्ट",
voice:"वॉयस",
input:"इनपुट",
pc:"पीसी",
mouseandqwer:"माउस और QWER",
clickanddrag:"(क्लिक और ड्रैग)",
uemigi:"↑→↓← और ZXCAS",
wasdandqecx:"WASD और QECX",
click0:"(क्लिक)",
gamepad:"गेम पैड",
smartphoneortablet:"स्मार्ट फोन या टैबलेट",
touchgestures:"टच जेस्चर",
onkeyboard:"कीबोर्ड पर",
onmouseandkeyboard:"माउस और कीबोर्ड पर",
customize:"अनुकूलित करें",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"अटैक और ओके",
skill1andcancel:"स्किल1 और रद्द करें",
skill2:"स्किल2",
skill3:"स्किल3",
skill4:"स्किल4",
pause:"पॉज़",
config:"विन्यास",
mute:"म्यूट",
vibration:"वाइब्रेशन",
mousedrag:"माउस ड्रैग",
click1:"क्लिक",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"स्पेस",
c:"C",
m:"M",
drag:"ड्रैग",
lowspecmode:"निम्न-स्पेक मोड",
back:"पीछे",
resetgame:"गेम रीसेट",
escape:"Esc",
enter:"Enter",
loading:"लोड हो रहा है...",
title1:"हिमारी मेइमेई बनाम स्यूकबस",
title2:"शूटिंग गेम",
gamestart:"गेम शुरू करें",
specialthanks:"विशेष धन्यवाद",
konnichiwa:"नमस्ते। मैं मेइमेई हिमारी हूँ।",
kyouha:"आज, मैं तीन स्यूकबस को हराने जा रही हूँ।",
thisgameq:"यह गेम माउस और QWER कीज़ का उपयोग करता है।",
thisgamew:"यह गेम WASD कीज़ का उपयोग करता है।",
thisgameup:"यह गेम एरो कीज़ का उपयोग करता है।",
thisgamepad:"यह गेम गेमपैड का उपयोग करता है।",
openning1:"सिक्के इकट्ठा करें और ड्रोन दुकान पर उपयोग करें",
openning2:"उपकरण और कौशल खरीदने के लिए उपयोग करें. शुरू करें",
voiceq:"चलो शुरू करते हैं!",
voicew:"वह गया!",
voicee:"अरे!",
voicer:"ऊओओओ!",
win:"मैं जीत गई! ऐसे ही चलते रहो।",
dead:"मेरा हो गया।",
gameend:"खेल खत्म हो गया है। बहुत बढ़िया।",
continue:"खेलने के लिए धन्यवाद।",
soundtest:"साउंड टेस्ट",
irasshai:"स्वागत है!",
thanks:"बहुत-बहुत धन्यवाद।",
tap:"टैप"},


//10
{title:"Konfigurasi",
graphics:"Grafis",
fullscreen:"Layar Penuh",
on:"• Aktif",
off:"• Nonaktif",
displayquality:"Kualitas Tampilan",
low:"Rendah",
middle:"Sedang",
high:"Tinggi",
ifthe1:"* jika game macet,",
ifthe2:"silakan gunakan ini.",
lang:"Bahasa",
volume:"Volume",
mastervolume:"Volume Utama",
bgm:"Musik Latar",
soundeffect:"Efek Suara",
voice:"Suara Karakter",
input:"Input",
pc:"PC",
mouseandqwer:"Mouse & QWER",
clickanddrag:"( Klik & Seret )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( Klik )",
gamepad:"Gamepad",
smartphoneortablet:"Ponsel Cerdas atau Tablet",
touchgestures:"Gerakan Sentuh",
onkeyboard:"Pada Keyboard",
onmouseandkeyboard:"Pada Mouse & Keyboard",
customize:"Sesuaikan",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Serang & OK",
skill1andcancel:"Keterampilan1 & Batal",
skill2:"Keterampilan2",
skill3:"Keterampilan3",
skill4:"Keterampilan4",
pause:"Jeda",
config:"Konfigurasi",
mute:"Bisu",
vibration:"Getaran",
mousedrag:"Seret Mouse",
click1:"Klik",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Spasi",
c:"C",
m:"M",
drag:"Seret",
lowspecmode:"mode spesifikasi rendah",
back:"kembali",
resetgame:"atur ulang permainan",
escape:"Esc",
enter:"Enter",
loading:"Memuat...",
title1:"Himari Meimei VS Succubus",
title2:"Game Menembak",
gamestart:"Mulai Game",
specialthanks:"Terima Kasih",
konnichiwa:"Halo. Aku Meimei Himari.",
kyouha:"Hari ini, aku akan mengalahkan tiga succubus.",
thisgameq:"Game ini menggunakan mouse dan tombol QWER.",
thisgamew:"Game ini menggunakan tombol WASD.",
thisgameup:"Game ini menggunakan tombol panah.",
thisgamepad:"Game ini menggunakan gamepad.",
openning1:"Kumpulkan koin dan gunakan di toko drone",
openning2:"Beli perlengkapan dan keterampilan. Mulai ",
voiceq:"Ayo mulai!",
voicew:"Itu dia!",
voicee:"Hei!",
voicer:"Ooohhhh!",
win:"Aku menang! Ayo teruskan seperti ini.",
dead:"Sudah selesai.",
gameend:"Itu akhir dari permainan. Kerja bagus.",
continue:"Terima kasih telah bermain.",
soundtest:"Uji Suara",
irasshai:"Selamat datang!",
thanks:"Terima kasih banyak.",
tap:"Ketuk"},


//11
{title:"Configurazione",
graphics:"Grafica",
fullscreen:"Schermo intero",
on:"• Attivo",
off:"• Disattivo",
displayquality:"Qualità dello schermo",
low:"Bassa",
middle:"Media",
high:"Alta",
ifthe1:"* Se il gioco si blocca,",
ifthe2:"utilizza questa opzione.",
lang:"Lingua",
volume:"Volume",
mastervolume:"Volume generale",
bgm:"Musica di sottofondo",
soundeffect:"Effetti sonori",
voice:"Voci",
input:"Input",
pc:"PC",
mouseandqwer:"Mouse e tasti QWER",
clickanddrag:"(Clicca e trascina)",
uemigi:"↑→↓← e ZXCAS",
wasdandqecx:"WASD e QECX",
click0:"(Clicca)",
gamepad:"Gamepad",
smartphoneortablet:"Smartphone o tablet",
touchgestures:"Gesti touch",
onkeyboard:"Su tastiera",
onmouseandkeyboard:"Su mouse e tastiera",
customize:"Personalizza",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Attacco e OK",
skill1andcancel:"Abilità 1 e Annulla",
skill2:"Abilità 2",
skill3:"Abilità 3",
skill4:"Abilità 4",
pause:"Pausa",
config:"Configurazione",
mute:"Muto",
vibration:"Vibrazione",
mousedrag:"Trascinamento",
click1:"Clic",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Spazio",
c:"C",
m:"M",
drag:"Trascinamento",
lowspecmode:"modalità a basse prestazioni",
back:"indietro",
resetgame:"ripristina partita",
escape:"Esc",
enter:"Enter",
loading:"Caricamento in corso...",
title1:"Himari Meimei VS Succubus",
title2:"Gioco sparatutto",
gamestart:"Inizia il gioco",
specialthanks:"Ringraziamenti",
konnichiwa:"Ciao. Sono Meimei Himari.",
kyouha:"Oggi dovrò sconfiggere tre succubi.",
thisgameq:"Questo gioco si gioca con il mouse e i tasti QWER.",
thisgamew:"Questo gioco si gioca con i tasti WASD.",
thisgameup:"Questo gioco si gioca con i tasti freccia.",
thisgamepad:"Questo gioco si gioca con un gamepad.",
openning1:"Raccogli le monete e usale nel negozio di droni ",
openning2:"acquistare equipaggiamento e abilità. Bene, cominciamo.",
voiceq:"Ci siamo!",
voicew:"Eccolo che va!",
voicee:"Ehi!",
voicer:"Ooohhhh!",
win:"Ho vinto! Continuiamo così.",
dead:"Ho finito.",
gameend:"Il gioco è terminato. Ottimo lavoro.",
continue:"Grazie per aver giocato.",
soundtest:"Prova audio",
irasshai:"Benvenuto!",
thanks:"Grazie mille.",
tap:"Tocco"},


//12
{title:"設定",
graphics:"グラフィック",
fullscreen:"全画面表示",
on:"• オン",
off:"• オフ",
displayquality:"画質",
low:"低",
middle:"中",
high:"高",
ifthe1:"* ゲームがクラッシュする場合は、",
ifthe2:"こちらをご利用ください。",
lang:"言語",
volume:"音量",
mastervolume:"マスター音量",
bgm:"BGM",
soundeffect:"効果音",
voice:"ボイス",
input:"入力",
pc:"PC",
mouseandqwer:"マウス & QWER",
clickanddrag:"( クリック & ドラッグ )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( クリック )",
gamepad:"ゲームパッド",
smartphoneortablet:"スマートフォンまたはタブレット",
touchgestures:"タッチジェスチャー",
onkeyboard:"キーボード",
onmouseandkeyboard:"マウス＆キーボード",
customize:"カスタマイズ",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"攻撃＆OK",
skill1andcancel:"スキル1＆キャンセル",
skill2:"スキル2",
skill3:"スキル3",
skill4:"スキル4",
pause:"一時停止",
config:"設定",
mute:"ミュート",
vibration:"バイブレーション",
mousedrag:"ドラッグ",
click1:"クリック",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"スペース",
c:"C",
m:"M",
drag:"ドラッグ",
lowspecmode:"低スペックモード",
back:"戻る",
resetgame:"ゲームをリセット",
escape:"Esc",
enter:"Enter",
loading:"ローディング中です",
title1:"冥鳴ひまり VS サキュバス",
title2:"シューティングゲーム",
gamestart:"ゲームスタート",
specialthanks:"スペシャルサンクス",
konnichiwa:"こんにちは。めいめいひまりです。",
kyouha:"今日はサキュバスを3人倒したいと思います。",
thisgameq:"このゲームはマウスとQWERボタンを使います。",
thisgamew:"このゲームはWASDボタンを使います。",
thisgameup:"このゲームは十字キーを使います。",
thisgamepad:"このゲームはゲームパッドを使います。",
openning1:"コインを集めて上から降りてくるドローンショップで",
openning2:"装備スキルを購入してください。それではまいりましょう。",
voiceq:"それーっ",
voicew:"そりゃー",
voicee:"えいっ",
voicer:"おっりゃああ",
win:"かちました。このままつづけてまいりましょう",
dead:"まいりました",
gameend:"これでゲームはしゅうりょうです。おつかれさまでした。",
continue:"つづけてくれてありがとう。",
soundtest:"サウンドテスト",
irasshai:"いらっしゃいませ",
thanks:"ありがとうございました",
tap:"タップ"},


//13
{title:"Konfigurasi",
graphics:"Grafis",
fullscreen:"Layar Penuh",
on:"• Nyala",
off:"• Mateni",
displayquality:"Kualitas Tampilan",
low:"Andhep",
middle:"Tengah",
high:"Dhuwur",
ifthe1:"* yen game macet,",
ifthe2:"mangga gunakake iki.",
lang:"Basa",
volume:"Volume",
mastervolume:"Volume Utama",
bgm:"BGM",
soundeffect:"Efek Swara",
voice:"Swara",
input:"Input",
pc:"PC",
mouseandqwer:"Mouse & QWER",
clickanddrag:"( Klik & Seret )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( Klik )",
gamepad:"Game Pad",
smartphoneortablet:"Smart Phone utawa Tablet",
touchgestures:"Gerakan Sentuh",
onkeyboard:"Ing Keyboard",
onmouseandkeyboard:"Ing Mouse & Keyboard",
customize:"Kustomisasi",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Serang & OK",
skill1andcancel:"Ketrampilan1 & Batal",
skill2:"Ketrampilan2",
skill3:"Ketrampilan3",
skill4:"Ketrampilan4",
pause:"Istirahat",
config:"Konfigurasi",
mute:"Mati Suara",
vibration:"Getaran",
mousedrag:"Seret Mouse",
click1:"Klik",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Space",
c:"C",
m:"M",
drag:"Seret",
lowspecmode:"mode spek rendah",
back:"mundur",
resetgame:"reset game",
escape:"Esc",
enter:"Enter",
loading:"Muat...",
title1:"Himari Meimei VS Succubus",
title2:"Game Tembak-Tembakan",
gamestart:"Miwiti Game",
specialthanks:"Panuwun Khusus",
konnichiwa:"Halo. Aku Meimei Himari.",
kyouha:"Dina iki, aku bakal ngalahake telung succubus.",
thisgameq:"Game iki nggunakake mouse lan tombol QWER.",
thisgamew:"Game iki nggunakake tombol WASD.",
thisgameup:"Game iki nggunakake tombol panah.",
thisgamepad:"Game iki nggunakake gamepad.",
openning1:"Kumpulna koin lan gunakna ing toko drone",
openning2:"tuku piranti lan katrampilan. Oke, ayo diwiwiti.",
voiceq:"Mangkene!",
voicew:"Mangkono!",
voicee:"Hei!",
voicer:"Ooohhhh!",
win:"Aku menang! Ayo terus kaya ngene.",
dead:"Aku rampung.",
gameend:"Iku pungkasané game. Apik tenan.",
continue:"Matur nuwun wis main.",
soundtest:"Uji Suara",
irasshai:"Sugeng rawuh!",
thanks:"Matur nuwun sanget.",
tap:"Tutul"},


//14
{title:"ಕಾನ್ಫಿಗರ್",
graphics:"ಗ್ರಾಫಿಕ್ಸ್",
fullscreen:"ಪೂರ್ಣ ಪರದೆ",
on:"• ಆನ್",
off:"• ಆಫ್",
displayquality:"ಪ್ರದರ್ಶನ ಗುಣಮಟ್ಟ",
low:"ಕಡಿಮೆ",
middle:"ಮಧ್ಯಮ",
high:"ಹೆಚ್ಚು",
ifthe1:"* ಆಟ ಕ್ರ್ಯಾಶ್ ಆಗಿದ್ದರೆ,",
ifthe2:"ದಯವಿಟ್ಟು ಇದನ್ನು ಬಳಸಿ.",
lang:"ಭಾಷೆ",
volume:"ಸಂಪುಟ",
mastervolume:"ಮಾಸ್ಟರ್ ವಾಲ್ಯೂಮ್",
bgm:"BGM",
soundeffect:"ಧ್ವನಿ ಪರಿಣಾಮ",
voice:"ಧ್ವನಿ",
input:"ಇನ್‌ಪುಟ್",
pc:"PC",
mouseandqwer:"ಮೌಸ್ & QWER",
clickanddrag:"( ಕ್ಲಿಕ್ & ಡ್ರ್ಯಾಗ್ )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( ಕ್ಲಿಕ್ )",
gamepad:"ಗೇಮ್ ಪ್ಯಾಡ್",
smartphoneortablet:"ಸ್ಮಾರ್ಟ್ ಫೋನ್ ಅಥವಾ ಟ್ಯಾಬ್ಲೆಟ್",
touchgestures:"ಟಚ್ ಗೆಸ್ಚರ್‌ಗಳು",
onkeyboard:"ಕೀಬೋರ್ಡ್‌ನಲ್ಲಿ",
onmouseandkeyboard:"ಮೌಸ್ ಕೀಲಿ",
customize:"ಕಸ್ಟಮೈಸ್ ಮಾಡಿ",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"ದಾಳಿ & ಸರಿ",
skill1andcancel:"ಸ್ಕಿಲ್1 & ರದ್ದುಮಾಡಿ",
skill2:"ಸ್ಕಿಲ್2",
skill3:"ಸ್ಕಿಲ್3",
skill4:"ಸ್ಕಿಲ್4",
pause:"ವಿರಾಮ",
config:"ಸಂರಚನಾ",
mute:"ಮ್ಯೂಟ್",
vibration:"ಕಂಪನ",
mousedrag:"ಮೌಸ್ ಡ್ರ್ಯಾಗ್",
click1:"ಕ್ಲಿಕ್ ಮಾಡಿ",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"ಸ್ಪೇಸ್",
c:"C",
m:"M",
drag:"ಡ್ರ್ಯಾಗ್",
lowspecmode:"ಕಡಿಮೆ ಸ್ಪೆಕ್‌ಮೋಡ್ ",
back:"ಹಿಂದೆ ",
resetgame:"ಮರುಹೊಂದಿಸಿಆಟ ",
escape:"Esc",
enter:"Enter",
loading:"ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
title1:"ಹಿಮರಿ ಮೀಮೆಯಿ VS ಸಕ್ಯೂಬಸ್",
title2:"ಶೂಟಿಂಗ್ ಆಟ",
gamestart:"ಆಟ ಪ್ರಾರಂಭಿಸಿ",
specialthanks:"ವಿಶೇಷ ಧನ್ಯವಾದ",
konnichiwa:"ಹಲೋ. ನಾನು ಮೀಮೆಯಿ ಹಿಮಾರಿ.",
kyouha:"ಇಂದು, ನಾನು ಮೂರು ಸಕ್ಯೂಬಿಗಳನ್ನು ಕೆಡವಲಿದ್ದೇನೆ.",
thisgameq:"ಈ ಆಟವು ಮೌಸ್ ಮತ್ತು QWER ಕೀಗಳನ್ನು ಬಳಸುತ್ತದೆ.",
thisgamew:"ಈ ಆಟವು WASD ಕೀಗಳನ್ನು ಬಳಸುತ್ತದೆ.",
thisgameup:"ಈ ಆಟವು ಬಾಣದ ಕೀಲಿಗಳನ್ನು ಬಳಸುತ್ತದೆ.",
thisgamepad:"ಈ ಆಟವು ಗೇಮ್‌ಪ್ಯಾಡ್ ಅನ್ನು ಬಳಸುತ್ತದೆ.",
openning1:"ನಾಣ್ಯಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ ಅಂಗಡಿಯಲ್ಲಿ ಬಳಸಿ",
openning2:"ಉಪಕರಣಗಳು, ಕೌಶಲ್ಯಗಳು ಖರೀದಿಸಿ ",
voiceq:"ಇಗೋ ನಾವು ಹೋಗುತ್ತೇವೆ!",
voicew:"ಇದೇನೇ ಹೋಗುತ್ತದೆ!",
voicee:"ಹೇ!",
voicer:"ಓಹ್ಹ್ಹ್!",
win:"ನಾನು ಗೆದ್ದೆ! ಹೀಗೆಯೇ ಮುಂದುವರಿಯೋಣ.",
dead:"ನಾನು ಮುಗಿಸಿದೆ.",
gameend:"ಅದು ಆಟದ ಅಂತ್ಯ. ಒಳ್ಳೆಯ ಕೆಲಸ.",
continue:"ಆಟವಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು.",
soundtest:"ಧ್ವನಿ ಪರೀಕ್ಷೆ",
irasshai:"ಸ್ವಾಗತ!",
thanks:"ತುಂಬಾ ಧನ್ಯವಾದಗಳು.Lōḍ āguttide...",
tap:"ಟ್ಯಾಪ್ ಮಾಡಿ "},


//15
{title:"설정",
graphics:"그래픽",
fullscreen:"전체 화면",
on:"• 켜기",
off:"• 끄기",
displayquality:"화질",
low:"낮음",
middle:"중간",
high:"높음",
ifthe1:"* 게임이 강제 종료될 경우,",
ifthe2:"이 설정을 사용해 주세요.",
lang:"언어",
volume:"음량",
mastervolume:"전체 음량",
bgm:"BGM",
soundeffect:"음향 효과",
voice:"음성",
input:"입력",
pc:"PC",
mouseandqwer:"마우스 & QWER",
clickanddrag:"( 클릭 & 드래그 )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( 클릭 )",
gamepad:"게임패드",
smartphoneortablet:"스마트폰 또는 태블릿",
touchgestures:"터치 제스처",
onkeyboard:"키보드",
onmouseandkeyboard:"마우스 및 키보드",
customize:"사용자 지정",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"공격 및 확인",
skill1andcancel:"스킬1 및 취소",
skill2:"스킬2",
skill3:"스킬3",
skill4:"스킬4",
pause:"일시 정지",
config:"설정",
mute:"음소거",
vibration:"진동",
mousedrag:"마우스 드래그",
click1:"클릭",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"스페이스",
c:"C",
m:"M",
drag:"드래그",
lowspecmode:"저사양 모드",
back:"뒤로",
resetgame:"게임 초기화",
escape:"Esc",
enter:"Enter",
loading:"로딩 중...",
title1:"메이메이 히마리 VS 서큐버스",
title2:"슈팅 게임",
gamestart:"게임 시작",
specialthanks:"특별 감사의 말",
konnichiwa:"안녕하세요. 저는 메이메이 히마리입니다.",
kyouha:"오늘은 서큐버스 세 마리를 쓰러뜨릴 거예요.",
thisgameq:"이 게임은 마우스와 QWER 키를 사용합니다.",
thisgamew:"이 게임은 WASD 키를 사용합니다.",
thisgameup:"이 게임은 화살표 키를 사용합니다.",
thisgamepad:"이 게임은 게임패드를 사용합니다.",
openning1:"코인을 모아서 위에서 내려오는 드론 상점에서",
openning2:"장비와 스킬을 구매하세요. 자, 시작해 볼까요.",
voiceq:"시작합니다!",
voicew:"저기 가네요!",
voicee:"이봐요!",
voicer:"우와아아!",
win:"이겼어요! 이 기세로 계속해 봅시다.",
dead:"다 끝났어요.",
gameend:"게임이 끝났습니다. 수고하셨습니다.",
continue:"플레이해 주셔서 감사합니다.",
soundtest:"사운드 테스트",
irasshai:"환영합니다!",
thanks:"대단히 감사합니다.",
tap:"탭"},


//16
{title:"Konfig",
graphics:"Grafik",
fullscreen:"Skrin Penuh",
on:"• Hidup",
off:"• Mati",
displayquality:"Kualiti Paparan",
low:"Rendah",
middle:"Sederhana",
high:"Tinggi",
ifthe1:"* jika permainan terhenti,",
ifthe2:"sila gunakan ini.",
lang:"Bahasa",
volume:"Jumlah Bunyi",
mastervolume:"Jumlah Bunyi Utama",
bgm:"BGM",
soundeffect:"Kesan Bunyi",
voice:"Suar",
input:"Input",
pc:"PC",
mouseandqwer:"Tetikus & QWER",
clickanddrag:"( Klik & Seret )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( Klik )",
gamepad:"Game Pad",
smartphoneortablet:"Telefon Pintar atau Tablet",
touchgestures:"Gerakan Sentuh",
onkeyboard:"Pada Papan Kekunci",
onmouseandkeyboard:"Tetikus & Kekunci",
customize:"Kustomisasi",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Serang & OK",
skill1andcancel:"Kebolehan1 & Batal",
skill2:"Kebolehan2",
skill3:"Kebolehan3",
skill4:"Kebolehan4",
pause:"Jeda",
config:"Konfig",
mute:"Bisu",
vibration:"Getaran",
mousedrag:"Seret Tetikus",
click1:"Klik",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Angkasa",
c:"C",
m:"M",
drag:"Seret",
lowspecmode:"mod spesifikasi rendah",
back:"ke belakang",
resetgame:"tetapkan semula permainan",
escape:"Esc",
enter:"Enter",
loading:"Memuat...",
title1:"Himari Meimei VS Succubus",
title2:"Permainan Tembak",
gamestart:"Mula Permainan",
specialthanks:"Terima Kasih",
konnichiwa:"Halo. Saya Meimei Himari.",
kyouha:"Hari ini, saya akan menewaskan tiga succubus.",
thisgameq:"Permainan ini menggunakan tetikus dan kekunci QWER.",
thisgamew:"Permainan ini menggunakan kekunci WASD.",
thisgameup:"Permainan ini menggunakan kekunci anak panah.",
thisgamepad:"Permainan ini menggunakan gamepad.",
openning1:"Kumpul syiling dan guna di kedai dron ",
openning2:"membeli peralatan dan kemahiran. Baiklah, jom mula.",
voiceq:"Jom!",
voicew:"Itu dia!",
voicee:"Hei!",
voicer:"Ooohhhh!",
win:"Saya menang! Teruskan begitu.",
dead:"Saya dah habis.",
gameend:"Itulah penghujung permainan. Tahniah.",
continue:"Terima kasih kerana bermain.",
soundtest:"Uji Bunyi",
irasshai:"Selamat datang!",
thanks:"Terima kasih banyak banyak.",
tap:"Ketuk"},


//17
{title:"കോൺഫിഗർ",
graphics:"ഗ്രാഫിക്സ്",
fullscreen:"ഫുൾ സ്ക്രീൻ",
on:"• ഓൺ",
off:"• ഓഫ്",
displayquality:"ഡിസ്പ്ലേ ക്വാളിറ്റി",
low:"കുറവ്",
middle:"മധ്യം",
high:"ഉയരം",
ifthe1:"* ഗെയിം ക്രേഷ് ആയാൽ,",
ifthe2:"ദയവായി ഇത് ഉപയോഗിക്കുക.",
lang:"ഭാഷ",
volume:"വോളിയം",
mastervolume:"മാസ്റ്റർ വോളിയം",
bgm:"BGM",
soundeffect:"സൗണ്ട് എഫക്റ്റ്",
voice:"വോയിസ്",
input:"ഇൻപുട്ട്",
pc:"പിസി",
mouseandqwer:"മൗസ് & QWER",
clickanddrag:"( ക്ലിക്ക് & ഡ്രാഗ് )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( ക്ലിക്ക് )",
gamepad:"ഗെയിം പാഡ്",
smartphoneortablet:"സ്മാർട്ട് ഉപകരണം",
touchgestures:"ടച്ച് ജെസ്റ്ററുകൾ",
onkeyboard:"കീയിൽ",
onmouseandkeyboard:"മൗസ് കീബോർഡ്",
customize:"ഇഷ്ടാനുസൃതമാക്കുക",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"ആക്രമം & ശരി",
skill1andcancel:"സ്കിൽ1 & റദ്ദ്",
skill2:"സ്കിൽ2",
skill3:"സ്കിൽ3",
skill4:"സ്കിൽ4",
pause:"പോസ്",
config:"ക്രമീകരണം",
mute:"മ്യൂട്ട്",
vibration:"വൈബ്രേഷൻ",
mousedrag:"മൗസ് ഡ്രാഗ്",
click1:"ക്ലിക്ക്",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"സ്പേസ്",
c:"C",
m:"M",
drag:"ഡ്രാഗ്",
lowspecmode:"ലോ മോഡ്",
back:"പിന്നോട്ട്",
resetgame:"ഗെയിം റീസെറ്റ് ചെയ്യുക",
escape:"Esc",
enter:"Enter",
loading:"ലോഡിംഗ്...",
    title1:"ഹിമാരി vs സുക്കൂബസ് പോരാട്ടം",
title2:"ഷൂട്ടിംഗ് ഗെയിം",
gamestart:"ആരംഭം",
specialthanks:"പ്രത്യേക നന്ദി",
konnichiwa:"ഹലോ. ഞാൻ മെയ്മെയ് ഹിമാരി ആണ്.",
kyouha:"ഇന്ന് മൂന്ന് സുക്കൂബികളെ തോൽപ്പിക്കും",
thisgameq:"മൗസ് + QWER കീകൾ ഉപയോഗിക്കും ",
thisgamew:"ഈ ഗെയിം WASD കീകൾ ഉപയോഗിക്കുന്നു.",
thisgameup:"ഈ ഗെയിം ആരോ കീകൾ ഉപയോഗിക്കുന്നു.",
thisgamepad:"ഈ ഗെയിം ഗെയിംപാഡ് ഉപയോഗിക്കുന്നു.",
openning1:"നാണയങ്ങൾ ശേഖരിച്ച് ഷോപ്പിൽ ഉപയോഗിക്കുക",
openning2:"ഉപകരണങ്ങൾ വാങ്ങാൻ ഉപയോഗിക്കുക. തുടങ്ങുക",
voiceq:"ഇതാ തുടങ്ങുന്നു!",
voicew:"അതാ പോയി!",
voicee:"ഹേയ്!",
voicer:"ഓഹ്ഹ്ഹ്!",
win:"ഞാൻ ജയിച്ചു! ഇങ്ങനെ തുടരാം.",
dead:"ഞാൻ കളിച്ചു തീർത്തു.",
gameend:"കളി അവസാനിച്ചു. നല്ല കളി.",
continue:"കളിച്ചതിന് നന്ദി.",
soundtest:"സൗണ്ട് ടെസ്റ്റ്",
irasshai:"സ്വാഗതം!",
thanks:"വളരെ നന്ദി.",
tap:"ടാപ്പ്"},


//18
{title:"संरचना",
graphics:"ग्राफिक्स",
fullscreen:"पूर्ण स्क्रीन",
on:"• चालू",
off:"• बंद",
displayquality:"प्रदर्शन गुणवत्ता",
low:"कमी",
middle:"मध्यम",
high:"उच्च",
ifthe1:"* जर गेम क्रॅश होत असेल,",
ifthe2:"तर कृपया हे वापरा.",
lang:"भाषा",
volume:"ध्वनी",
mastervolume:"मास्टर व्हॉल्यूम",
bgm:"BGM",
soundeffect:"ध्वनी प्रभाव",
voice:"व्हॉइस",
input:"इनपुट",
pc:"पीसी",
mouseandqwer:"माउस आणि QWER",
clickanddrag:"(क्लिक आणि ड्रॅग)",
uemigi:"↑→↓← आणि ZXCAS",
wasdandqecx:"WASD आणि QECX",
click0:"(क्लिक)",
gamepad:"गेम पॅड",
smartphoneortablet:"स्मार्टफोन किंवा टॅबलेट",
touchgestures:"टच जेस्चर",
onkeyboard:"कीबोर्डवर",
onmouseandkeyboard:"माउस आणि कीबोर्डवर",
customize:"सानुकूलित करा",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"आक्रमण आणि ठीक आहे",
skill1andcancel:"कौशल्य1 आणि रद्द करा",
skill2:"कौशल्य2",
skill3:"कौशल्य3",
skill4:"कौशल्य4",
pause:"विराम",
config:"संरचना",
mute:"म्यूट",
vibration:"कंपन",
mousedrag:"माउस ड्रॅग",
click1:"क्लिक",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"स्पेस",
c:"C",
m:"M",
drag:"ड्रॅग",
lowspecmode:"कमी विनिर्देश मोड",
back:"मागे",
resetgame:"खेळ रीसेट करा",
escape:"Esc",
enter:"Enter",
loading:"लोड होत आहे...",
title1:"हिमारी मेईमेई विरुद्ध स्युक्कबस",
title2:"शूटिंग गेम",
gamestart:"गेम सुरू करा",
specialthanks:"विशेष आभार",
konnichiwa:"नमस्कार. मी मेईमेई हिमारी आहे.",
kyouha:"आज मी तीन स्यूक्युब्सना हरवणार आहे.",
thisgameq:"या खेळात माउस आणि QWER कीज वापरल्या जातात.",
thisgamew:"या खेळात WASD कीज वापरल्या जातात.",
thisgameup:"या खेळात ऍरो कीज वापरल्या जातात.",
thisgamepad:"या खेळात गेमपॅड वापरला जातो.",
openning1:"नाणी गोळा करा आणि ड्रोन दुकानात वापरा ",
openning2:"खरेदी करण्यासाठी वापरा. ठीक आहे, चला सुरू करूया.",
voiceq:"चला सुरू करुया!",
voicew:"घेऊन गेलं!",
voicee:"अरे!",
voicer:"ओह्ह्ह्ह!",
win:"मी जिंकलो! असंच सुरू ठेवूया.",
dead:"मी झालो.",
gameend:"खेळाचा शेवट झाला. छान काम.",
continue:"खेळल्याबद्दल धन्यवाद.",
soundtest:"ध्वनी चाचणी",
irasshai:"स्वागत आहे!",
thanks:"खूप खूप धन्यवाद.",
tap:"टॅप"},


//19
{title:"ဆက်တင်",
graphics:"ဂရပ်ဖစ်",
fullscreen:"ပြည့်မျက်နှာပြင်",
on:"• ဖွင့်",
off:"• ပိတ်",
displayquality:"ပြသအရည်အသွေး",
low:"နိမ့်",
middle:"အလတ်",
high:"မြင့်",
ifthe1:"* ဂိမ်းပျက်သွားပါက၊",
ifthe2:"ဒီကို အသုံးပြုပါ။",
lang:"ဘာသာစကား",
volume:"အသံ",
mastervolume:"မဟာအသံ",
bgm:"နောက်ခံဂီတ",
soundeffect:"အသံထွက်",
voice:"အသံ",
input:"အင်ပွတ်",
pc:"PC",
mouseandqwer:"Mouse & QWER",
clickanddrag:"( နှိပ်ပြီး ဆွဲ )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( နှိပ် )",
gamepad:"ဂိမ်းပက်",
smartphoneortablet:"စမတ်ဖုန်း သို့မဟုတ် တက်ဘလက်",
touchgestures:"ထိတွေ့ အမိန့်များ",
onkeyboard:"ကီးဘုတ်ပေါ်တွင်",
onmouseandkeyboard:"မောက်စ်နှင့် ကီးဘုတ်ပေါ်တွင်",
customize:"စိတ်ကြိုက်ပြင်ဆင်ရန်",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"တိုက်ခိုက် & OK",
skill1andcancel:"ကျွမ်းကျင်မှု၁ & ဖျက်",
skill2:"ကျွမ်းကျင်မှု၂",
skill3:"ကျွမ်းကျင်မှု၃",
skill4:"ကျွမ်းကျင်မှု၄",
pause:"ရပ်",
config:"ပြင်ဆင်ချက်",
mute:"အသံပိတ်",
vibration:"လှုပ်ခါ",
mousedrag:"မောက်စ်ဆွဲခြင်း",
click1:"နှိပ်ခြင်း",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Space",
c:"C",
m:"M",
drag:"ဆွဲခြင်း",
lowspecmode:"အလွယ်မုဒ် ",
back:"နောက်ပြန်",
resetgame:"ဂိမ်းပြန်စတင်",
escape:"Esc",
enter:"Enter",
loading:"တင်နေပြီ...",
title1:"ဟီမာရီ မေမိ VS ဆက်ကဘတ်",
title2:"ပစ်ခတ်ဂိမ်း",
gamestart:"ဂိမ်းစတင်",
specialthanks:"အထူးကျေးဇူးတင်",
konnichiwa:"မင်္ဂလာပါ။ ကျွန်မက မေမိ ဟီမာရီပါ။",
kyouha:"ဒီနေ့ succubi သုံးကောင်ကို အနိုင်ယူမယ်။",
thisgameq:"ဒီဂိမ်းမှာ မောက်စ်နဲ့ QWER ခလုတ်တွေကို အသုံးပြုတယ်။",
thisgamew:"ဒီဂိမ်းမှာ WASD ခလုတ်တွေကို အသုံးပြုတယ်။",
thisgameup:"ဒီဂိမ်းမှာ အာရို ခလုတ်တွေကို အသုံးပြုတယ်။",
thisgamepad:"ဒီဂိမ်းမှာ ဂိမ်းပက်ကို အသုံးပြုတယ်။",
openning1:"ငွေကြေးတွေကို စုဆောင်းပြီး အပေါ်က ဆင်းလာမယ့် ဒရုန်းဆိုင်မှာ",
openning2:"ပစ္စည်း၊ ကျွမ်းကျင်မှု ဝယ်ဖို့ အသုံးပြုပါ။ စတင်ကြစို့ ",
voiceq:"စလိုက်ကြရအောင်!",
voicew:"သွားပြီ!",
voicee:"ဟေ့!",
voicer:"အိုအိုအို!",
win:"ငါအနိုင်ရပြီ! ဒီလိုဆက်ကစားကြရအောင်။",
dead:"ပြီးသွားပြီ။",
gameend:"ဂိမ်းပြီးဆုံးပါပြီ။ ကောင်းပြီ။",
continue:"ကစားပေးတဲ့အတွက် ကျေးဇူးတင်ပါတယ်။",
soundtest:"အသံစမ်းသပ်ခြင်း",
irasshai:"ကြိုဆိုပါသည်!",
thanks:"အထူးကျေးဇူးတင်ပါတယ်။",
tap:"ထိခြင်း"},


//20
{title:"କନଫିଗରେସନ୍‌",
graphics:"ଗ୍ରାଫିକ୍ସ",
fullscreen:"ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍‌",
on:"• ଚାଲୁ",
off:"• ବନ୍ଦ",
displayquality:"ପ୍ରଦର୍ଶିତ ଗୁଣବତ୍ତା",
low:"ନିମ୍ନ",
middle:"ମଧ୍ୟମ",
high:"ଉଚ୍ଚ",
ifthe1:"* ଯଦି ଖେଳଟି କ୍ରାସ୍ ହୁଏ,",
ifthe2:"ଦୟାକରି ଏହାକୁ ବ୍ୟବହାର କରନ୍ତୁ।",
lang:"ଭାଷା",
volume:"ଭଲ୍ୟୁମ୍‌",
mastervolume:"ମାଷ୍ଟର୍‌ ଭଲ୍ୟୁମ୍‌",
bgm:"BGM",
soundeffect:"ଧ୍ୱନି ପ୍ରଭାବ",
voice:"ଭଏସ୍‌",
input:"ଇନପୁଟ୍‌",
pc:"ପିସି‌",
mouseandqwer:"ମାଉସ୍‌ ଏବଂ QWER",
clickanddrag:"( କ୍ଲିକ୍‌ ଏବଂ ଡ୍ରାଗ୍‌ )",
uemigi:"↑→↓← ଏବଂ ZXCAS",
wasdandqecx:"WASD ଏବଂ QECX",
click0:"( କ୍ଲିକ୍‌ )",
gamepad:"ଗେମ୍‌ ପ୍ୟାଡ୍‌",
smartphoneortablet:"ସ୍ମାର୍ଟ ଫୋନ୍‌ କିମ୍ବା ଟାବଲେଟ୍‌",
touchgestures:"ସ୍ପର୍ଶ ଜେଶ୍ଚର୍‌",
onkeyboard:"କୀବୋର୍ଡ୍‌ରେ",
onmouseandkeyboard:"ମାଉସ୍‌ ଏବଂ କୀବୋର୍ଡ୍‌ରେ",
customize:"କଷ୍ଟମାଇଜ୍‌",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"ଆକ୍ରମଣ ଏବଂ ଠିକ୍‌",
skill1andcancel:"ଦକ୍ଷତା1 ଏବଂ ବାତିଲ୍‌",
skill2:"ଦକ୍ଷତା2",
skill3:"ଦକ୍ଷତା3",
skill4:"ଦକ୍ଷତା4",
pause:"ବିରାମ‌",
config:"କନଫିଗରେସନ୍‌",
mute:"ମ୍ୟୁଟ୍‌",
vibration:"କମ୍ପନ‌",
mousedrag:"ମାଉସ୍‌ ଡ୍ରାଗ୍‌",
click1:"କ୍ଲିକ୍‌",
q:"ପ୍ରଶ୍ନ",
w:"W",
e:"E",
r:"R",
space:"ସ୍ଥାନ",
c:"C",
m:"M",
drag:"ଡ୍ରାଗ୍‌",
lowspecmode:"ଲୋସ୍ପେକମୋଡ୍‌ ",
back:"ପଛକୁ ",
resetgame:"ରିସେଟ୍‌ଗେମ୍‌ ",
escape:"Esc",
enter:"Enter",
loading:"ଲୋଡ୍ ହେଉଛି...",
title1:"ହିମାରି ମେଇମେଇ VS ସୁକୁବସ୍",
title2:"ସୁଟିଂ ଖେଳ",
gamestart:"ଖେଳ ଆରମ୍ଭ କରନ୍ତୁ",
specialthanks:"ବିଶେଷ ଧନ୍ୟବାଦ",
konnichiwa:"ନମସ୍କାର। ମୁଁ ମେଇମେଇ ହିମାରି। ",
kyouha:"ଆଜି, ମୁଁ ତିନୋଟି ସୁକୁବି କାଟିବାକୁ ଯାଉଛି।",
thisgameq:"ଏହି ଖେଳଟି ମାଉସ୍ ଏବଂ QWER କୀ ବ୍ୟବହାର କରେ।",
thisgamew:"ଏହି ଖେଳଟି WASD କୀ ବ୍ୟବହାର କରେ।",
thisgameup:"ଏହି ଖେଳଟି ତୀର କୀ ବ୍ୟବହାର କରେ।",
thisgamepad:"ଏହି ଖେଳଟି ଏକ ଗେମପ୍ୟାଡ୍ ବ୍ୟବହାର କରେ। ",
openning1:"ମୁଦ୍ରା ସଂଗ୍ରହ କରି ଡ୍ରୋନ୍ ଦୋକାନରେ ଖର୍ଚ୍ଚ କରନ୍ତୁ",
openning2:"ଉପକରଣ ଏବଂ ଦକ୍ଷତା କିଣନ୍ତୁ। ଠିକ୍ ଅଛି, ଆରମ୍ଭ କରିବା।",
voiceq:"ଏଇ ଦେଖ!",
voicew:"ଏଇ ଦେଖ!",
voicee:"ଏଇ ଦେଖ!",
voicer:"ଓଃ!",
win:"ମୁଁ ଜିତିଲି! ଆସନ୍ତୁ ଏହିପରି ଜାରି ରଖିବା।",
dead:"ମୋର କାମ ସରିଗଲା।",
gameend:"ଏହା ଖେଳର ଶେଷ। ଭଲ କାମ।",
continue:"ଖେଳିବା ପାଇଁ ଧନ୍ୟବାଦ।",
soundtest:"ଶବ୍ଦ ପରୀକ୍ଷା",
irasshai:"ସ୍ୱାଗତ!",
thanks:"ବହୁତ ବହୁତ ଧନ୍ୟବାଦ। ",
tap:"ଟ୍ୟାପ୍‌ "},

//右から書く
//21
{title:"تنظیمات",
graphics:"گرافیک",
fullscreen:"تمام‌صفحه",
on:"روشن •",
off:"خاموش •",
displayquality:"کیفیت نمایش",
low:"پایین",
middle:"متوسط",
high:"بالا",
ifthe1:"اگر بازی کرش کرد، *",
ifthe2:"لطفاً از این استفاده کنید.",
lang:"زبان",
volume:"حجم صدا",
mastervolume:"حجم صدای اصلی",
bgm:"موسیقی پس‌زمینه",
soundeffect:"افکت صوتی",
voice:"صدا",
input:"ورودی",
pc:"کیبورد",
mouseandqwer:"ماوس و QWER",
clickanddrag:"( کلیک و کشیدن )",
uemigi:"↑→↓← و ZXCAS",
wasdandqecx:"WASD و QECX",
click0:"( کلیک )",
gamepad:"پد بازی",
smartphoneortablet:"گوشی هوشمند یا تبلت",
touchgestures:"ژست‌های لمسی",
onkeyboard:"روی صفحه‌کلید",
onmouseandkeyboard:"روی ماوس و صفحه‌کلید",
customize:"سفارشی‌سازی",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"حمله و تأیید",
skill1andcancel:"مهارت۱ و لغو",
skill2:"مهارت۲",
skill3:"مهارت۳",
skill4:"مهارت۴",
pause:"مکث",
config:"تنظیمات",
mute:"بی‌صدا",
vibration:"لرزش",
mousedrag:"کشیدن ماوس",
click1:"کلیک",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Space",
c:"C",
m:"M",
drag:"کشیدن",
lowspecmode:"حالت کم‌سروصدا",
back:"بازگشت",
resetgame:"ریست بازی",
escape:"Esc",
enter:"Enter",
loading:"در حال بارگذاری...",
title1:"هیماری میمی در مقابل سوکوبوس",
title2:"بازی تیراندازی",
gamestart:"شروع بازی",
specialthanks:"تشکر ویژه",
konnichiwa:"سلام. من میمی هیماری هستم.",
kyouha:"امروز قصد دارم سه ساکوبوس را شکست دهم.",
thisgameq:"این بازی با ماوس و کلیدهای QWER کنترل می‌شود.",
thisgamew:"این بازی با کلیدهای WASD کنترل می‌شود.",
thisgameup:"این بازی با کلیدهای جهت‌نما کنترل می‌شود.",
thisgamepad:"این بازی با گیم‌پد کنترل می‌شود.",
openning1:"سکه جمع‌آوری کنید و از آنها در فروشگاه پهپاد که از بالا پایین می‌آید برای",
openning2:"خرید تجهیزات و مهارت‌ها استفاده کنید. خب، بیایید شروع کنیم.",
voiceq:"برویم!",
voicew:"رفت!",
voicee:"هی!",
voicer:"اوووه!",
win:"بردم! بیایید همین‌طور ادامه بدیم.",
dead:"تمام شد.",
gameend:"این پایان بازی است. آفرین.",
continue:"ممنون که بازی کردید.",
soundtest:"آزمایش صدا",
irasshai:"خوش آمدید!",
thanks:"خیلی ممنون.",
tap:"لمس"},


//22
{title:"Ustawienia",
graphics:"Grafika",
fullscreen:"Pełny ekran",
on:"• Włączone",
off:"• Wyłączone",
displayquality:"Jakość obrazu",
low:"Niska",
middle:"Średnia",
high:"Wysoka",
ifthe1:"* jeśli gra się zawiesza,",
ifthe2:"proszę skorzystać z tej opcji.",
lang:"Język",
volume:"Głośność",
mastervolume:"Głośność ogólna",
bgm:"Muzyka w tle",
soundeffect:"Efekty dźwiękowe",
voice:"Głosy",
input:"Sterowanie",
pc:"PC",
mouseandqwer:"Mysz i klawisze QWER",
clickanddrag:"(Kliknij i przeciągnij)",
uemigi:"↑→↓← i klawisze ZXCAS",
wasdandqecx:"WASD i klawisze QECX",
click0:"(Kliknij)",
gamepad:"Pad",
smartphoneortablet:"Smartfon lub tablet",
touchgestures:"Gesty dotykowe",
onkeyboard:"Na klawiaturze",
onmouseandkeyboard:"Na myszy i klawiaturze",
customize:"Dostosuj",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Atak i OK",
skill1andcancel:"Umiejętność 1 i Anuluj",
skill2:"Umiejętność 2",
skill3:"Umiejętność 3",
skill4:"Umiejętność 4",
pause:"Pauza",
config:"Konfiguracja",
mute:"Wycisz",
vibration:"Wibracja",
mousedrag:"Przeciąganie",
click1:"Kliknięcie",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Spacja",
c:"C",
m:"M",
drag:"Przeciąganie",
lowspecmode:"ryb niskich wymagań",
back:"wstecz",
resetgame:"zresetuj grę",
escape:"Esc",
enter:"Enter",
loading:"Ładowanie...",
title1:"Himari Meimei kontra Succubus",
title2:"Gra strzelanka",
gamestart:"Rozpocznij grę",
specialthanks:"Podziękowania",
konnichiwa:"Witam. Nazywam się Meimei Himari.",
kyouha:"Dzisiaj pokonam trzy sukkuby.",
thisgameq:"W tej grze używa się myszki i klawiszy QWER.",
thisgamew:"W tej grze używa się klawiszy WASD.",
thisgameup:"W tej grze używa się klawiszy strzałek.",
thisgamepad:"W tej grze używa się gamepada.",
openning1:"Zbieraj monety i wydawaj w sklepie dronów ",
openning2:"kupić sprzęt i umiejętności. No dobrze, zaczynamy.",
voiceq:"Zaczynamy!",
voicew:"I już!",
voicee:"Hej!",
voicer:"Ooohhhh!",
win:"Wygrałem! Kontynuujmy w tym stylu.",
dead:"Skończyłem.",
gameend:"To koniec gry. Dobra robota.",
continue:"Dziękujemy za grę.",
soundtest:"Test dźwięku",
irasshai:"Witaj!",
thanks:"Bardzo dziękuję.",
tap:"Dotknięcie"},


//23
{title:"Configurações",
graphics:"Gráficos",
fullscreen:"Tela cheia",
on:"• Ativado",
off:"• Desativado",
displayquality:"Qualidade da imagem",
low:"Baixa",
middle:"Média",
high:"Alta",
ifthe1:"* se o jogo travar,",
ifthe2:"use esta opção.",
lang:"Idioma",
volume:"Volume",
mastervolume:"Volume geral",
bgm:"Música de fundo",
soundeffect:"Efeitos sonoros",
voice:"Vozes",
input:"Controles",
pc:"PC",
mouseandqwer:"Mouse e QWER",
clickanddrag:"(Clique e arraste)",
uemigi:"↑→↓← e ZXCAS",
wasdandqecx:"WASD e QECX",
click0:"(Clique)",
gamepad:"Controle",
smartphoneortablet:"Smartphone ou Tablet",
touchgestures:"Gestos de Toque",
onkeyboard:"No Teclado",
onmouseandkeyboard:"No Mouse e Teclado",
customize:"Personalizar",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Ataque e OK",
skill1andcancel:"Habilidade 1 e Cancelar",
skill2:"Habilidade 2",
skill3:"Habilidade 3",
skill4:"Habilidade 4",
pause:"Pausa",
config:"Configuração",
mute:"Silenciar",
vibration:"Vibração",
mousedrag:"Arraste",
click1:"Clicar",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Espaço",
c:"C",
m:"M",
drag:"Arrastar",
lowspecmode:"modo de baixa resolução",
back:"voltar",
resetgame:"reiniciar jogo",
escape:"Esc",
enter:"Enter",
loading:"A carregar...",
title1:"Himari Meimei VS Succubus",
title2:"Jogo de tiro",
gamestart:"Iniciar jogo",
specialthanks:"Agradecimentos",
konnichiwa:"Olá. Sou a Meimei Himari.",
kyouha:"Hoje, vou derrotar três súcubos.",
thisgameq:"Este jogo utiliza o rato e as teclas QWER.",
thisgamew:"Este jogo utiliza as teclas WASD.",
thisgameup:"Este jogo utiliza as setas do teclado.",
thisgamepad:"Este jogo utiliza um comando.",
openning1:"Recolhe moedas e usa as na loja de drones ",
openning2:"comprar equipamento e habilidades. Muito bem, vamos começar.",
voiceq:"Aqui vamos nós!",
voicew:"Lá vai ele!",
voicee:"Ei!",
voicer:"Ooohhhh!",
win:"Ganhei! Vamos continuar assim.",
dead:"Acabei.",
gameend:"É o fim do jogo. Bom trabalho.",
continue:"Obrigado por jogares.",
soundtest:"Teste de som",
irasshai:"Bem vindo!",
thanks:"Muito obrigado.",
tap:"Tocar"},


//24
{title:"ਸੰਰਚਨਾ",
graphics:"ਗ੍ਰਾਫਿਕਸ",
fullscreen:"ਪੂਰੀ ਸਕ੍ਰੀਨ",
on:"• ਚਾਲੂ",
off:"• ਬੰਦ",
displayquality:"ਡਿਸਪਲੇ ਗੁਣਵੱਤਾ",
low:"ਘੱਟ",
middle:"ਦਰਮਿਆਨਾ",
high:"ਵੱਧ",
ifthe1:"* ਜੇ ਗੇਮ ਕਰੈਸ਼ ਹੋ ਜਾਂਦੀ ਹੈ,",
ifthe2:"ਕਿਰਪਾ ਕਰਕੇ ਇਸਦੀ ਵਰਤੋਂ ਕਰੋ।",
lang:"ਭਾਸ਼ਾ",
volume:"ਆਵਾਜ਼",
mastervolume:"ਮਾਸਟਰ ਵੌਲਿਊਮ",
bgm:"ਬੀ.ਜੀ.ਐੱਮ.",
soundeffect:"ਧੁਨੀ ਪ੍ਰਭਾਵ",
voice:"ਆਵਾਜ਼",
input:"ਇਨਪੁੱਟ",
pc:"ਪੀਸੀ",
mouseandqwer:"ਮਾਊਸ ਅਤੇ QWER",
clickanddrag:"( ਕਲਿੱਕ ਅਤੇ ਡਰੈਗ )",
uemigi:"↑→↓← ਅਤੇ ZXCAS",
wasdandqecx:"WASD ਅਤੇ QECX",
click0:"( ਕਲਿੱਕ )",
gamepad:"ਗੇਮ ਪੈਡ",
smartphoneortablet:"ਸਮਾਰਟ ਫੋਨ ਜਾਂ ਟੈਬਲੇਟ",
touchgestures:"ਟੱਚ ਇਸ਼ਾਰੇ",
onkeyboard:"ਕੀਬੋਰਡ' ਤੇ",
onmouseandkeyboard:"ਮਾਊਸ ਅਤੇ ਕੀਬੋਰਡ' ਤੇ",
customize:"ਕਸਟਮਾਈਜ਼",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"ਹਮਲਾ ਅਤੇ ਠੀਕ ਹੈ",
skill1andcancel:"ਹੁਨਰ1 ਅਤੇ ਰੱਦ ਕਰੋ",
skill2:"ਹੁਨਰ2",
skill3:"ਹੁਨਰ3",
skill4:"ਹੁਨਰ4",
pause:"ਰੋਕੋ",
config:"ਸੈਟਿੰਗ",
mute:"ਖਾਮੋਸ਼",
vibration:"ਕੰਪਨ",
mousedrag:"ਮਾਊਸ ਡਰੈਗ",
click1:"ਕਲਿੱਕ",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"ਸਪੇਸ",
c:"C",
m:"M",
drag:"ਡਰੈਗ",
lowspecmode:"ਘੱਟ-ਸਪੈਕ ਮੋਡ",
back:"ਪਿੱਛੇ",
resetgame:"ਗੇਮ ਰੀਸੈੱਟ",
escape:"Esc",
enter:"Enter",
loading:"ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
title1:"ਹਿਮਾਰੀ ਮੇਈਮੇਈ ਬਨਾਮ ਸੱਕਿਊਬਸ",
title2:"ਸ਼ੂਟਿੰਗ ਗੇਮ",
gamestart:"ਗੇਮ ਸ਼ੁਰੂ ਕਰੋ",
specialthanks:"ਖਾਸ ਧੰਨਵਾਦ",
konnichiwa:"ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ। ਮੈਂ ਮੇਈਮੇਈ ਹਿਮਾਰੀ ਹਾਂ।",
kyouha:"ਅੱਜ, ਮੈਂ ਤਿੰਨ ਸੱਕੂਬੀ ਨੂੰ ਹਰਾਉਣ ਜਾ ਰਹੀ ਹਾਂ।",
thisgameq:"ਇਹ ਗੇਮ ਮਾਊਸ ਅਤੇ QWER ਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ।",
thisgamew:"ਇਹ ਗੇਮ WASD ਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ।",
thisgameup:"ਇਹ ਗੇਮ ਐਰੋ ਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ।",
thisgamepad:"ਇਹ ਗੇਮ ਗੇਮਪੈਡ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ।",
openning1:"ਸਿੱਕੇ ਇਕੱਠੇ ਕਰੋ ਅਤੇ ਉਨ੍ਹਾਂ ਦੀ ਵਰਤੋਂ ਉੱਪਰੋਂ ਹੇਠਾਂ ਆਉਣ ਵਾਲੀ ਡਰੋਨ ਦੁਕਾਨ' ਤੇ",
openning2:"ਸਾਜ਼ੋ-ਸਾਮਾਨ ਅਤੇ ਹੁਨਰ ਖਰੀਦਣ ਲਈ ਕਰੋ। ਠੀਕ ਹੈ, ਚਲੋ ਸ਼ੁਰੂ ਕਰੀਏ।",
voiceq:"ਚਲੋ ਸ਼ੁਰੂ ਕਰੀਏ!",
voicew:"ਇਹ ਹੋ ਗਿਆ!",
voicee:"ਹੇ!",
voicer:"ਓਓਓਓ!",
win:"ਮੈਂ ਜਿੱਤ ਗਿਆ! ਆਓ ਇਸੇ ਤਰ੍ਹਾਂ ਜਾਰੀ ਰੱਖੀਏ।",
dead:"ਮੈਂ ਖਤਮ ਕਰ ਲਿਆ।",
gameend:"ਇਹ ਗੇਮ ਦਾ ਅੰਤ ਹੈ। ਸ਼ਾਬਾਸ਼।",
continue:"ਖੇਡਣ ਲਈ ਧੰਨਵਾਦ।",
soundtest:"ਸਾਊਂਡ ਟੈਸਟ",
irasshai:"ਸੁਆਗਤ ਹੈ!",
thanks:"ਤੁਹਾਡਾ ਬਹੁਤ ਧੰਨਵਾਦ।",
tap:"ਟੈਪ"},


//25
{title:"Настройки",
graphics:"Графика",
fullscreen:"Полный экран",
on:"• Вкл.",
off:"• Выкл.",
displayquality:"Качество изображения",
low:"Низкое",
middle:"Среднее",
high:"Высокое",
ifthe1:"* если игра вылетает,",
ifthe2:"пожалуйста, воспользуйтесь этим.",
lang:"Язык",
volume:"Громкость",
mastervolume:"Общая громкость",
bgm:"Фоновая музыка",
soundeffect:"Звуковые эффекты",
voice:"Голосовые диалоги",
input:"Управление",
pc:"ПК",
mouseandqwer:"Мышь и QWER",
clickanddrag:"(Клик и перетаскивание)",
uemigi:"↑→↓← и ZXCAS",
wasdandqecx:"WASD и QECX",
click0:"(Клик)",
gamepad:"Геймпад",
smartphoneortablet:"Смартфон или планшет",
touchgestures:"Сенсорные жесты",
onkeyboard:"На клавиатуре",
onmouseandkeyboard:"На мыши и клавиатуре",
customize:"Настройка",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Атака и OK",
skill1andcancel:"Навык 1 и Отмена",
skill2:"Навык 2",
skill3:"Навык 3",
skill4:"Навык 4",
pause:"Пауза",
config:"Настройки",
mute:"Без звука",
vibration:"Вибрация",
mousedrag:"Перетаскивание",
click1:"Щелчок",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Пробел",
c:"C",
m:"M",
drag:"Перетаскивание",
lowspecmode:"облегчённый режим",
back:"назад",
resetgame:"сбросить игру",
escape:"Esc",
enter:"Enter",
loading:"Загрузка...",
title1:"Химари Мэймэй против суккуба",
title2:"Стрелялка",
gamestart:"Начать игру",
specialthanks:"Благодарность",
konnichiwa:"Здравствуйте. Я  Мэймэй Химари.",
kyouha:"Сегодня я собираюсь победить трех суккубов.",
thisgameq:"В этой игре используются мышь и клавиши QWER.",
thisgamew:"В этой игре используются клавиши WASD.",
thisgameup:"В этой игре используются клавиши со стрелками.",
thisgamepad:"В этой игре используется геймпад.",
openning1:"Собирайте монеты и тратьте в магазине дронов ",
openning2:"покупать снаряжение и навыки. Ладно, приступим.",
voiceq:"Поехали!",
voicew:"Вот и он!",
voicee:"Эй!",
voicer:"Ооооо!",
win:"Я победила! Давайте продолжим в том же духе.",
dead:"Я закончила.",
gameend:"Игра закончилась. Молодец.",
continue:"Спасибо, что сыграли.",
soundtest:"Тест звука",
irasshai:"Добро пожаловать!",
thanks:"Большое спасибо.",
tap:"Нажатие"},

//26
{title:"Configuración",
graphics:"Gráficos",
fullscreen:"Pantalla completa",
on:"• Activado",
off:"• Desactivado",
displayquality:"Calidad de imagen",
low:"Baja",
middle:"Media",
high:"Alta",
ifthe1:"* Si el juego se cuelga,",
ifthe2:"utiliza esta opción.",
lang:"Idioma",
volume:"Volumen",
mastervolume:"Volumen general",
bgm:"Música de fondo",
soundeffect:"Efectos de sonido",
voice:"Voces",
input:"Entrada",
pc:"PC",
mouseandqwer:"Ratón y QWER",
clickanddrag:"(Hacer clic y arrastrar)",
uemigi:"↑→↓← y ZXCAS",
wasdandqecx:"WASD y QECX",
click0:"(Hacer clic)",
gamepad:"Mando",
smartphoneortablet:"Teléfono inteligente o tableta",
touchgestures:"Gestos táctiles",
onkeyboard:"En el teclado",
onmouseandkeyboard:"En ratón y teclado",
customize:"Personalizar",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Ataque y Aceptar",
skill1andcancel:"Habilidad 1 y Cancelar",
skill2:"Habilidad 2",
skill3:"Habilidad 3",
skill4:"Habilidad 4",
pause:"Pausa",
config:"Configuración",
mute:"Silenciar",
vibration:"Vibración",
mousedrag:"Arrastrar",
click1:"Hacer clic",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Espacio",
c:"C",
m:"M",
drag:"Arrastrar",
lowspecmode:"modo de bajo rendimiento",
back:"atrás",
resetgame:"reiniciar partida",
escape:"Esc",
enter:"Enter",
loading:"Cargando...",
title1:"Himari Meimei contra Succubus",
title2:"Juego de disparos",
gamestart:"Empezar partida",
specialthanks:"Agradecimientos",
konnichiwa:"Hola. Soy Meimei Himari.",
kyouha:"Hoy voy a acabar con tres súcubos.",
thisgameq:"Este juego se controla con el ratón y las teclas QWER.",
thisgamew:"Este juego se controla con las teclas WASD.",
thisgameup:"Este juego se controla con las teclas de flecha.",
thisgamepad:"Este juego se controla con un mando.",
openning1:"Recoge monedas y úsalas en la tienda de drones ",
openning2:"comprar equipamiento y habilidades. Muy bien, empecemos.",
voiceq:"¡Allá vamos!",
voicew:"¡Ahí va!",
voicee:"¡Eh!",
voicer:"¡Ooohhhh!",
win:"¡He ganado! Sigamos así.",
dead:"He terminado.",
gameend:"Se acabó el juego. Buen trabajo.",
continue:"Gracias por jugar.",
soundtest:"Prueba de sonido",
irasshai:"¡Bienvenido!",
thanks:"Muchas gracias.",
tap:"Tocar"},


//27
{title:"அமைப்பு",
graphics:"கிராபிக்ஸ்",
fullscreen:"முழுத்திரை",
on:"• ஆன்",
off:"• ஆஃப்",
displayquality:"காட்சித் தரம்",
low:"குறைந்த",
middle:"நடுத்தர",
high:"உயர்",
ifthe1:"* விளையாட்டு செயலிழந்தால்,",
ifthe2:"தயவுசெய்து இதைப் பயன்படுத்தவும்.",
lang:"மொழி",
volume:"ஒலி அளவு",
mastervolume:"முதன்மை ஒலி அளவு",
bgm:"பின்னணி இசை",
soundeffect:"ஒலி விளைவு",
voice:"குரல்",
input:"உள்ளீடு",
pc:"பிசி",
mouseandqwer:"மவுஸ் & QWER",
clickanddrag:"( கிளிக் & இழு)",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( கிளிக் )",
gamepad:"கேம் பேட்",
smartphoneortablet:"ஸ்மார்ட் சாதனம்",
touchgestures:"தொடு சைகைகள்",
onkeyboard:"விசையில்",
onmouseandkeyboard:"மவுஸ் விசையில்",
customize:"தனிப்பயனாக்கு",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"தாக்கு & சரி",
skill1andcancel:"திறன்1 & ரத்துசெய்",
skill2:"திறன்2",
skill3:"திறன்3",
skill4:"திறன்4",
pause:"நிறுத்து",
config:"கட்டமைப்பு",
mute:"ஒலி அணை",
vibration:"அதிர்வு",
mousedrag:"இழுத்தல்",
click1:"சொடுக்கு",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"வெளிவிசை",
c:"C",
m:"M",
drag:"இழுத்தல்",
lowspecmode:"குறைந்த விவரம்",
back:"பின்",
resetgame:"விளையாட்டை மீட்டமை",
escape:"Esc",
enter:"Enter",
loading:"ஏற்றுகிறது...",
title1:"ஹிமாரி மேய்மேய் எதிர் சக்கப்ஸ்",
title2:"சுடுதல் விளையாட்டு",
gamestart:"தொடங்கு",
specialthanks:"நன்றிகள்",
konnichiwa:"வணக்கம். நான் மேய்மேய் ஹிமாரி.",
kyouha:"இன்று மூன்று சக்குபஸ்களை வீழ்த்துவேன் ",
thisgameq:"மவுஸ் + QWER விசைகள் பயன்படும் ",
thisgamew:"WASD விசைகள் பயன்படும் ",
thisgameup:"அம்பு விசைகள் பயன்படும் ",
thisgamepad:"கேம்பேட் பயன்படும் ",
openning1:"நாணயங்களைச் சேகரித்து ட்ரோன் கடையில் வையுங்கள்",
openning2:"உபகரணங்கள், திறன்கள் வாங்க பயன்படுத்துங்கள். தொடங்கு",
voiceq:"இதோ தொடங்குகிறோம்!",
voicew:"அது போகிறது!",
voicee:"ஏய்!",
voicer:"ஓஓஓஓ!",
win:"நான் வென்றுவிட்டேன்! இப்படித்தானே தொடர்வோம்.",
dead:"நான் முடித்துவிட்டேன்.",
gameend:"இதுதான் விளையாட்டின் முடிவு. நல்ல வேலை.",
continue:"விளையாடியதற்கு நன்றி.",
soundtest:"ஒலி சோதனை",
irasshai:"நல்வரவு!",
thanks:"மிகவும் நன்றி.",
tap:"தட்டவும்"},


//28
{title:"కాన్ఫిగ్",
graphics:"గ్రాఫిక్స్",
fullscreen:"ఫుల్ స్క్రీన్",
on:"• ఆన్",
off:"• ఆఫ్",
displayquality:"డిస్‌ప్లే నాణ్యత",
low:"తక్కువ",
middle:"మధ్యస్థం",
high:"అధికం",
ifthe1:"* గేమ్ క్రాష్ అయితే,",
ifthe2:"దయచేసి దీనిని ఉపయోగించండి.",
lang:"భాష",
volume:"వాల్యూమ్",
mastervolume:"మాస్టర్ వాల్యూమ్",
bgm:"BGM",
soundeffect:"సౌండ్ ఎఫెక్ట్",
voice:"వాయిస్",
input:"ఇన్‌పుట్",
pc:"PC",
mouseandqwer:"మౌస్ & QWER",
clickanddrag:"( క్లిక్ & డ్రాగ్ )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( క్లిక్ )",
gamepad:"గేమ్ ప్యాడ్",
smartphoneortablet:"స్మార్ట్ ఫోన్ లేదా టాబ్లెట్",
touchgestures:"టచ్ జెస్చర్లు",
onkeyboard:"కీబోర్డ్‌పై",
onmouseandkeyboard:"మౌస్ & కీబోర్డ్‌పై",
customize:"కస్టమైజ్",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"దాడి & ఓకే",
skill1andcancel:"స్కిల్1 & రద్దు",
skill2:"స్కిల్2",
skill3:"స్కిల్3",
skill4:"స్కిల్4",
pause:"పాజ్",
config:"కాన్ఫిగ్",
mute:"మ్యూట్",
vibration:"వైబ్రేషన్",
mousedrag:"మౌస్ డ్రాగ్",
click1:"క్లిక్",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"స్పేస్",
c:"C",
m:"M",
drag:"డ్రాగ్",
lowspecmode:"తక్కువ స్పెసిఫికేషన్ల మోడ్",
back:"వెనక్కి",
resetgame:"గేమ్‌ను రీసెట్ చేయండి",
escape:"Esc",
enter:"Enter",
loading:"లోడ్ అవుతోంది...",
title1:"హిమారి మేమే VS సక్కబస్",
title2:"షూటింగ్ గేమ్",
gamestart:"ప్రారంభించండి",
specialthanks:"ధన్యవాదాలు",
konnichiwa:"నమస్కారం. నేను మేమే హిమారి.",
kyouha:"ఈ రోజు, నేను మూడు సక్కూబీలను ఓడించబోతున్నాను.",
thisgameq:"ఈ గేమ్ మౌస్ మరియు QWER కీలను ఉపయోగిస్తుంది.",
thisgamew:"ఈ గేమ్ WASD కీలను ఉపయోగిస్తుంది.",
thisgameup:"ఈ గేమ్ ఆరో కీలను ఉపయోగిస్తుంది.",
thisgamepad:"ఈ గేమ్ గేమ్‌ప్యాడ్‌ను ఉపయోగిస్తుంది.",
openning1:"నాణేలు తీసుకుని డ్రోన్ షాపులో ఖర్చు చేయి ",
openning2:"పరికరాలు, నైపుణ్యాల కోసం వాడండి. ప్రారంభిద్దాం",
voiceq:"ఇదిగో మొదలుపెట్టాం!",
voicew:"అది వెళ్ళింది!",
voicee:"హే!",
voicer:"ఓహ్హ్హ్!",
win:"నేను గెలిచాను! ఇలాగే కొనసాగిద్దాం.",
dead:"నేను పూర్తి చేశాను.",
gameend:"ఆట ముగిసింది. మంచి పని.",
continue:"ఆడినందుకు ధన్యవాదాలు.",
soundtest:"సౌండ్ టెస్ట్",
irasshai:"స్వాగతం!",
thanks:"చాలా ధన్యవాదాలు.",
tap:"ట్యాప్"},


//29
{title:"การตั้งค่า",
graphics:"กราฟิก",
fullscreen:"เต็มหน้าจอ",
on:"• เปิด",
off:"• ปิด",
displayquality:"คุณภาพการแสดงผล",
low:"ต่ำ",
middle:"กลาง",
high:"สูง",
ifthe1:"* หากเกมล่ม",
ifthe2:"โปรดใช้การตั้งค่านี้",
lang:"ภาษา",
volume:"ระดับเสียง",
mastervolume:"ระดับเสียงหลัก",
bgm:"เพลงประกอบ",
soundeffect:"เอฟเฟกต์เสียง",
voice:"เสียงพูด",
input:"อินพุต",
pc:"พีซี",
mouseandqwer:"เมาส์และ QWER",
clickanddrag:"(คลิกและลาก)",
uemigi:"↑→↓← และ ZXCAS",
wasdandqecx:"WASD และ QECX",
click0:"(คลิก)",
gamepad:"จอยเกม",
smartphoneortablet:"สมาร์ทโฟนหรือแท็บเล็ต",
touchgestures:"ท่าทางสัมผัส",
onkeyboard:"บนคีย์บอร์ด",
onmouseandkeyboard:"บนเมาส์และคีย์บอร์ด",
customize:"ปรับแต่ง",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"โจมตีและตกลง",
skill1andcancel:"สกิล 1 และยกเลิก",
skill2:"สกิล 2",
skill3:"สกิล 3",
skill4:"สกิล 4",
pause:"หยุดชั่วคราว",
config:"การตั้งค่า",
mute:"ปิดเสียง",
vibration:"การสั่น",
mousedrag:"ลากเมาส์",
click1:"คลิก",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Space",
c:"C",
m:"M",
drag:"ลาก",
lowspecmode:"โหมดสเปคต่ำ ",
back:"กลับ ",
resetgame:"รีเซ็ตเกม ",
escape:"Esc",
enter:"Enter",
loading:"กำลังโหลด...",
title1:"ฮิมาริ เมเม ปะทะ ซัคคิวบัส",
title2:"เกมยิงปืน",
gamestart:"เริ่มเกม",
specialthanks:"ขอบคุณเป็นพิเศษ",
konnichiwa:"สวัสดี ฉันคือเมเม ฮิมาริ",
kyouha:"วันนี้ ฉันจะกำจัดซัคคิวบัสสามตัว",
thisgameq:"เกมนี้ใช้เมาส์และปุ่ม QWER",
thisgamew:"เกมนี้ใช้ปุ่ม WASD",
thisgameup:"เกมนี้ใช้ปุ่มลูกศร",
thisgamepad:"เกมนี้ใช้จอยเกม",
openning1:"เก็บเหรียญและใช้มันที่ร้านโดรนที่ตกลงมาจากด้านบนเพื่อ",
openning2:"ซื้ออุปกรณ์และทักษะ เอาล่ะ มาเริ่มกันเลย",
voiceq:"ไปกันเลย!",
voicew:"ไปแล้ว!",
voicee:"เฮ้!",
voicer:"โอ้วววว!",
win:"ฉันชนะแล้ว! ลุยกันต่อแบบนี้แหละ",
dead:"เสร็จแล้ว",
gameend:"จบเกมแล้ว ทำได้ดีมาก",
continue:"ขอบคุณที่เล่นเกมนี้",
soundtest:"ทดสอบเสียง",
irasshai:"ยินดีต้อนรับ!",
thanks:"ขอบคุณมากครับ/ค่ะ ",
tap:"แตะ "},


//30
{title:"Ayarlar",
graphics:"Grafikler",
fullscreen:"Tam Ekran",
on:"• Açık",
off:"• Kapalı",
displayquality:"Görüntü Kalitesi",
low:"Düşük",
middle:"Orta",
high:"Yüksek",
ifthe1:"* Oyun çökerse,",
ifthe2:"lütfen bunu kullanın.",
lang:"Dil",
volume:"Ses Seviyesi",
mastervolume:"Genel Ses Seviyesi",
bgm:"Arka Plan Müziği",
soundeffect:"Ses Efekti",
voice:"Ses",
input:"Giriş",
pc:"PC",
mouseandqwer:"Fare & QWER",
clickanddrag:"( Tıkla ve Sürükle )",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"( Tıkla )",
gamepad:"Oyun Kumandası",
smartphoneortablet:"Akıllı Telefon veya Tablet",
touchgestures:"Dokunma Hareketleri",
onkeyboard:"Klavye Üzerinde",
onmouseandkeyboard:"Fare ve Klavye Üzerinde",
customize:"Özelleştir",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Saldırı ve Tamam",
skill1andcancel:"Beceri 1 ve İptal",
skill2:"Beceri 2",
skill3:"Beceri 3",
skill4:"Beceri 4",
pause:"Duraklat",
config:"Ayarlar",
mute:"Sessiz",
vibration:"Titreşim",
mousedrag:"Fare Sürükle",
click1:"Tıkla",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Boşluk",
c:"C",
m:"M",
drag:"Sürükle",
lowspecmode:"düşük özellik modu",
back:"geri",
resetgame:"oyunu sıfırla",
escape:"Esc",
enter:"Enter",
loading:"Yükleniyor...",
title1:"Himari Meimei VS Succubus",
title2:"Atış Oyunu",
gamestart:"Oyuna Başla",
specialthanks:"Özel Teşekkürler",
konnichiwa:"Merhaba. Ben Meimei Himari.",
kyouha:"Bugün üç succubus'u alt edeceğim.",
thisgameq:"Bu oyunda fare ve QWER tuşları kullanılır.",
thisgamew:"Bu oyunda WASD tuşları kullanılır.",
thisgameup:"Bu oyunda ok tuşları kullanılır.",
thisgamepad:"Bu oyunda oyun kumandası kullanılır.",
openning1:"Paraları topla ve drone dükkânında kullan ",
openning2:"ekipman ve beceriler satın al. Tamam, hadi başlayalım.",
voiceq:"Başlıyoruz!",
voicew:"İşte gidiyor!",
voicee:"Hey!",
voicer:"Ooohhhh!",
win:"Kazandım! Böyle devam edelim.",
dead:"Bitti.",
gameend:"Oyun sona erdi. Aferin.",
continue:"Oynadığınız için teşekkürler.",
soundtest:"Ses Testi",
irasshai:"Hoş geldiniz!",
thanks:"Çok teşekkür ederim.",
tap:"Dokun"},


//31
{title:"Налаштування",
graphics:"Графіка",
fullscreen:"Повний екран",
on:"• Увімкнути",
off:"• Вимкнути",
displayquality:"Якість зображення",
low:"Низька",
middle:"Середня",
high:"Висока",
ifthe1:"* якщо гра вилітає,",
ifthe2:"будь ласка, скористайтеся цим.",
lang:"Мова",
volume:"Гучність",
mastervolume:"Загальна гучність",
bgm:"Фонова музика",
soundeffect:"Звукові ефекти",
voice:"Голос",
input:"Управління",
pc:"ПК",
mouseandqwer:"Миша та QWER",
clickanddrag:"(Клік та перетягування)",
uemigi:"↑→↓← та ZXCAS",
wasdandqecx:"WASD та QECX",
click0:"(Клік)",
gamepad:"Геймпад",
smartphoneortablet:"Смартфон або планшет",
touchgestures:"Жести",
onkeyboard:"На клавіатурі",
onmouseandkeyboard:"На миші та клавіатурі",
customize:"Налаштувати",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Атака та OK",
skill1andcancel:"Навичка1 та Скас",
skill2:"Навичка2",
skill3:"Навичка3",
skill4:"Навичка4",
pause:"Пауза",
config:"Налаштування",
mute:"Вимкнути звук",
vibration:"Вібрація",
mousedrag:"Перетягування",
click1:"Клік",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Пробіл",
c:"C",
m:"M",
drag:"Перетягування",
lowspecmode:"полегшений режим",
back:"назад",
resetgame:"перезапустити гру",
escape:"Esc",
enter:"Enter",
loading:"Завантаження...",
title1:"Хімарі Меймей проти сукубу",
title2:"Стрілялка",
gamestart:"Почати гру",
specialthanks:"Подяка",
konnichiwa:"Привіт. Я — Меймей Хімарі.",
kyouha:"Сьогодні я збираюся перемогти трьох сукубів.",
thisgameq:"У цій грі використовуються миша та клавіші QWER.",
thisgamew:"У цій грі використовуються клавіші WASD.",
thisgameup:"У цій грі використовуються клавіші зі стрілками.",
thisgamepad:"У цій грі використовується геймпад.",
openning1:"Збирайте монети та витрачайте у дрон‑магазині зверху",
openning2:"придбати спорядження та навички. Гаразд, почнемо.",
voiceq:"Поїхали!",
voicew:"Ось і все!",
voicee:"Гей!",
voicer:"Ооооо!",
win:"Я виграв! Давайте продовжувати в тому ж дусі.",
dead:"Я закінчив.",
gameend:"Це кінець гри. Молодець.",
continue:"Дякуємо за гру.",
soundtest:"Тест звуку",
irasshai:"Ласкаво просимо!",
thanks:"Дуже дякуємо.",
tap:"Натискання"},


//32
{title:"تشکیل",
graphics:"گرافکس",
fullscreen:"فل اسکرین",
on:"آن •",
off:"آف •",
displayquality:"ڈسپلے کوالٹی",
low:"کم",
middle:"درمیانی",
high:"زیادہ",
ifthe1:"اگر گیم کریش ہو جائے، *",
ifthe2:"تو براہ کرم اس کا استعمال کریں۔",
lang:"زبان",
volume:"آواز",
mastervolume:"ماسٹر والیوم",
bgm:"بی جی ایم",
soundeffect:"ساؤنڈ ایفیکٹ",
voice:"آواز",
input:"ان پٹ",
pc:"پی سی",
mouseandqwer:"ماؤس اور QWER",
clickanddrag:"( کلک اور ڈریگ )",
uemigi:"↑→↓← اور ZXCAS",
wasdandqecx:"WASD اور QECX",
click0:"( کلک )",
gamepad:"گیم پیڈ",
smartphoneortablet:"اسمارٹ فون یا ٹیبلٹ",
touchgestures:"ٹچ اشارے",
onkeyboard:"کی بورڈ پر",
onmouseandkeyboard:"ماؤس اور کی بورڈ پر",
customize:"حسبِ منشا",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"حملہ اور ٹھیک ہے",
skill1andcancel:"ہنر1 اور منسوخ کریں",
skill2:"ہنر2",
skill3:"ہنر3",
skill4:"ہنر4",
pause:"وقف",
config:"تشکیل",
mute:"خاموشی",
vibration:"کمپن",
mousedrag:"ماؤس ڈریگ",
click1:"کلک",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"اسپیس",
c:"C",
m:"M",
drag:"ڈریگ",
lowspecmode:"کم گرافیکس",
back:"واپس",
resetgame:"گیم ری سیٹ",
escape:"Esc",
enter:"Enter",
loading:"لوڈ ہو رہا ہے...",
title1:"ہیماری می می بمقابلہ سکوبی",
title2:"شوٹنگ گیم",
gamestart:"گیم شروع کریں",
specialthanks:"خصوصی شکریہ",
konnichiwa:"ہیلو۔ میں می می ہیماری ہوں۔",
kyouha:"آج میں تین سکیوبی کو شکست دوں گی۔",
thisgameq:"یہ کھیل ماؤس اور QWER کیز استعمال کرتا ہے۔",
thisgamew:"یہ کھیل WASD کیز استعمال کرتا ہے۔",
thisgameup:"یہ کھیل ایرو کیز استعمال کرتا ہے۔",
thisgamepad:"یہ کھیل گیم پیڈ استعمال کرتا ہے۔",
openning1:"سکے جمع کریں اور انہیں اوپر سے نیچے آنے والی ڈرون شاپ پر استعمال کریں تاکہ",
openning2:"سامان اور مہارتیں خریدیں۔ ٹھیک ہے، چلیں شروع کرتے ہیں۔",
voiceq:"یہ لو شروع!",
voicew:"یہ گیا!",
voicee:"ارے!",
voicer:"اوہہہہ!",
win:"میں جیت گیا! چلو ایسے ہی جاری رکھتے ہیں۔",
dead:"میرا ہو گیا۔",
gameend:"یہ کھیل کا اختتام ہے۔ شاباش۔",
continue:"کھیلنے کے لیے شکریہ۔",
soundtest:"آواز کا ٹیسٹ",
irasshai:"خوش آمدید!",
thanks:"بہت بہت شکریہ۔",
tap:"ٹیپ"},


//33
{title:"Cài đặt",
graphics:"Đồ họa",
fullscreen:"Toàn màn hình",
on:"• Bật",
off:"• Tắt",
displayquality:"Chất lượng hiển thị",
low:"Thấp",
middle:"Trung bình",
high:"Cao",
ifthe1:"* Nếu trò chơi bị treo,",
ifthe2:"vui lòng sử dụng tùy chọn này.",
lang:"Ngôn ngữ",
volume:"Âm lượng",
mastervolume:"Âm lượng chung",
bgm:"Nhạc nền",
soundeffect:"Hiệu ứng âm thanh",
voice:"Giọng nói",
input:"Điều khiển",
pc:"PC",
mouseandqwer:"Chuột & QWER",
clickanddrag:"(Nhấp và kéo)",
uemigi:"↑→↓← & ZXCAS",
wasdandqecx:"WASD & QECX",
click0:"(Nhấp)",
gamepad:"Bộ điều khiển",
smartphoneortablet:"Điện thoại thông minh hoặc máy tính bảng",
touchgestures:"Cử chỉ cảm ứng",
onkeyboard:"Trên bàn phím",
onmouseandkeyboard:"Trên chuột & bàn phím",
customize:"Tùy chỉnh",
up:"↑",
right:"→",
down:"↓",
left:"←",
attackandok:"Tấn công & OK",
skill1andcancel:"Kỹ năng 1 & Hủy",
skill2:"Kỹ năng 2",
skill3:"Kỹ năng 3",
skill4:"Kỹ năng 4",
pause:"Tạm dừng",
config:"Cài đặt",
mute:"Tắt tiếng",
vibration:"Rung",
mousedrag:"Kéo chuột",
click1:"Nhấp",
q:"Q",
w:"W",
e:"E",
r:"R",
space:"Space",
c:"C",
m:"M",
drag:"Kéo",
lowspecmode:"chế độ cấu hình thấp",
back:"quay lại",
resetgame:"khởi động lại trò chơi",
escape:"Esc",
enter:"Enter",
loading:"Đang tải...",
title1:"Meimei Himari VS Succubus",
title2:"Trò chơi bắn súng",
gamestart:"Bắt đầu trò chơi",
specialthanks:"Lời cảm ơn",
konnichiwa:"Xin chào. Mình là Himari Meimei.",
kyouha:"Hôm nay, tôi sẽ tiêu diệt ba con succubus.",
thisgameq:"Trò chơi này sử dụng chuột và các phím QWER.",
thisgamew:"Trò chơi này sử dụng các phím WASD.",
thisgameup:"Trò chơi này sử dụng các phím mũi tên.",
thisgamepad:"Trò chơi này sử dụng gamepad.",
openning1:"Thu thập xu và dùng ở cửa hàng drone trên cao",
openning2:"mua trang bị và kỹ năng. Được rồi, bắt đầu thôi.",
voiceq:"Bắt đầu nào!",
voicew:"Nó đi rồi!",
voicee:"Này!",
voicer:"Ooohhhh!",
win:"Tớ thắng rồi! Cứ tiếp tục như thế này nhé.",
dead:"Tớ xong rồi.",
gameend:"Trò chơi kết thúc tại đây. Làm tốt lắm.",
continue:"Cảm ơn bạn đã chơi.",
soundtest:"Kiểm tra âm thanh",
irasshai:"Chào mừng!",
thanks:"Cảm ơn rất nhiều.",
tap:"Nhấn"}];
